import {animationUtils} from '../../proxy.mjs';
async function move(token, positions) {
    positions = positions.map(i => ({x: i.x + token.object.w / 2, y: i.y + token.object.h / 2}));
    for (let e = 0; e < positions.length; e++) {
        if (e == 0) {
            /* eslint-disable indent */
            await new Sequence()
                .animation()
                    .on(token)
                    .opacity(0)
                    .snapToGrid()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.01')
                    .atLocation(token)
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x:-1}, {gridUnits: true})
                .effect()
                    .file('jb2a.particles.outward.white.01.03')
                    .atLocation(token)
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .fadeOut(200)
                    .scaleIn(0, 200, {ease: 'easeOutCubic'})
                    .animateProperty('sprite', 'width', {from: 0, to: 2, duration: 500, gridUnits: true, ease: 'easeOutBack'})
                    .animateProperty('sprite', 'height', {from: 0, to: 0.5, duration: 1000, gridUnits: true, ease: 'easeOutBack'})
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .spriteOffset({x: -1.25}, {gridUnits : true})
                    .zIndex(0.4)
                .effect()
                    .file('jb2a.smoke.puff.side.dark_black.4')
                    .atLocation(token)
                    .scaleToObject(2)
                    .rotateTowards(positions[e])
                    .fadeOut(200)
                    .opacity(1)
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .spriteRotation(180)
                    .spriteOffset({x: -1.75}, {gridUnits: true})
                    .moveSpeed(1500)
                    .zIndex(0.3)
                .effect()
                    .file('jb2a.energy_strands.range.standard.grey')
                    .atLocation(token)
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(0.5)
                    .repeats(3,50,50)
                    .spriteOffset({x:0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.2)
                .effect()
                    .file('animated-spell-effects-cartoon.magic.mind sliver')
                    .delay(50)
                    .atLocation(token)
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(1)
                    .spriteOffset({x:0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.21)
                .effect()
                    .copySprite(token)
                    .name('Dash')
                    .atLocation(token)
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .duration(400)
                    .fadeIn(400, {ease: 'easeOutCirc'})
                    .fadeOut(0)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .scale(token.texture.scaleX)
                    .waitUntilFinished(-300)
                .effect()
                    .delay(200)
                    .copySprite(token)
                    .scale(token.texture.scaleX)
                    .atLocation(positions[e])
                    .fadeOut(500, {ease: 'easeOutQuad'})
                    .duration(1000)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .opacity(1)
                    .playIf(positions.length == 1)
                .animation()
                    .delay(200)
                    .on(token)
                    .teleportTo(positions[e])
                    .snapToGrid()
                    .opacity(1)
                    .playIf(positions.length == 1)
                .play();
            /* eslint-enable indent */
            if (positions.length === 1) await token.actor.sheet.maximize();
        } else if (e == positions.length - 1){
            /* eslint-disable indent */
            await new Sequence()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.43')
                    .atLocation(positions[e-1])
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x: -1}, {gridUnits: true})
                    .randomRotation()
                .effect()
                    .file('jb2a.particles.outward.white.01.03')
                    .atLocation(positions[e-1])
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .fadeOut(200)
                    .scaleIn(0, 200, {ease: 'easeOutCubic'})
                    .animateProperty('sprite', 'width', {from: 0, to: 2, duration: 500, gridUnits: true, ease: 'easeOutBack'})
                    .animateProperty('sprite', 'height', {from: 0, to: 0.5, duration: 1000, gridUnits: true, ease: 'easeOutBack'})
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .spriteOffset({x: -1.25}, {gridUnits: true})
                    .zIndex(0.4)
                .effect()
                    .file('jb2a.smoke.puff.side.dark_black.4')
                    .atLocation(positions[e-1])
                    .scaleToObject(2)
                    .rotateTowards(positions[e])
                    .fadeOut(200)
                    .opacity(1)
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .spriteRotation(180)
                    .spriteOffset({x: -1.75}, {gridUnits: true})
                    .moveSpeed(1500)
                    .zIndex(0.3)
                .effect()
                    .file('jb2a.energy_strands.range.standard.grey')
                    .atLocation(positions[e-1])
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(0.5)
                    .repeats(3,50,50)
                    .spriteOffset({x: 0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.2)
                .effect()
                    .file('animated-spell-effects-cartoon.magic.mind sliver')
                    .delay(50)
                    .atLocation(positions[e-1])
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(1)
                    .spriteOffset({x: 0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.21)
                .effect()
                    .copySprite(token)
                    .name('Dash')
                    .atLocation(positions[e-1])
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .duration(400)
                    .fadeIn(400, {ease: 'easeOutCirc'})
                    .fadeOut(0)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .scale(token.texture.scaleX)
                    .waitUntilFinished(-300)
                .effect()
                    .delay(200)
                    .copySprite(token)
                    .scale(token.texture.scaleX)
                    .atLocation(positions[e])
                    .fadeOut(500, {ease: 'easeOutQuad'})
                    .duration(1000)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .opacity(1)
                .animation()
                    .delay(200)
                    .on(token)
                    .teleportTo(positions[e])
                    .snapToGrid()
                    .opacity(1)
                .play();
            /* eslint-enable indent */
            await token.actor.sheet.maximize();
        } else {
            /* eslint-disable indent */
            await new Sequence()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.43')
                    .atLocation(positions[e-1])
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x: -1}, {gridUnits: true})
                    .randomRotation()
                .effect()
                    .file(`jb2a.particles.outward.white.01.03`)
                    .atLocation(positions[e-1])
                    .rotateTowards(positions[e])
                    .scaleToObject(1.75)
                    .fadeOut(200)
                    .scaleIn(0, 200, {ease: 'easeOutCubic'})
                    .animateProperty('sprite', 'width', {from: 0, to: 2, duration: 500, gridUnits: true, ease:'easeOutBack'})
                    .animateProperty('sprite', 'height', {from: 0, to: 0.5, duration: 1000, gridUnits: true, ease:'easeOutBack'})
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .spriteOffset({x: -1.25}, {gridUnits: true})
                    .zIndex(0.4)
                .effect()
                    .file('jb2a.smoke.puff.side.dark_black.4')
                    .atLocation(positions[e-1])
                    .scaleToObject(2)
                    .rotateTowards(positions[e])
                    .fadeOut(200)
                    .opacity(1)
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .spriteRotation(180)
                    .spriteOffset({x: -1.75}, {gridUnits: true})
                    .moveSpeed(1500)
                    .zIndex(0.3)
                .effect()
                    .file('jb2a.energy_strands.range.standard.grey')
                    .atLocation(positions[e-1])
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(0.5)
                    .repeats(3,50,50)
                    .spriteOffset({x: 0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.2)
                .effect()
                    .file('animated-spell-effects-cartoon.magic.mind sliver')
                    .delay(50)
                    .atLocation(positions[e-1])
                    .stretchTo(positions[e])
                    .belowTokens()
                    .opacity(1)
                    .spriteOffset({x: 0}, {gridUnits: true})
                    .filter('ColorMatrix', {saturate: -1})
                    .randomizeMirrorY()
                    .fadeOut(200)
                    .zIndex(0.21)
                .effect()
                    .copySprite(token)
                    .name('Dash')
                    .atLocation(positions[e-1])
                    .moveTowards(positions[e],{rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .duration(400)
                    .fadeIn(400, {ease: 'easeOutCirc'})
                    .fadeOut(0)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .scale(token.texture.scaleX)
                    .waitUntilFinished(-300)
                .play();
            /* eslint-enable indent */
        } 
    }
}
export const cunningActionDash = {
    name: 'CHRISPREMADES.Animations.CunningActionDash.Name',
    macros: {
        move
    },
    inputs: ['token', 'positions'],
    requirements: ['jb2a_patreon', 'animated-spell-effects-cartoon'],
    type: 'classFeature',
    get credits() {
        return [animationUtils.getEskieCredits()];
    }
};