import {animationUtils} from '../../proxy.mjs';
async function move(token, positions) {
    positions = positions.map(i => ({x: i.x + token.object.w / 2, y: i.y + token.object.h / 2}));
    for (let e = 0; e < positions.length; e++) {
        if(e == 0) {
            /* eslint-disable indent */
            await new Sequence()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.43')
                    .atLocation(token)
                    .rotateTowards(positions[e])
                    .size(token.width * 1.75, {gridUnits: true})
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x: -1}, {gridUnits: true})
                    .randomRotation()
                .animation()
                    .on(token)
                    .opacity(0)
                    .snapToGrid()
                .effect()
                    .copySprite(token)
                    .name('Disengage')
                    .atLocation(token)
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .duration(1500)
                    .fadeOut(0)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .scale(token.texture.scaleX * 0.9)
                    .filter('ColorMatrix', {brightness: -1})
                    .filter('Blur', {blurX: 5, blurY: 10})
                    .opacity(0.6)
                    .scaleIn(0.5, 300, {ease: 'easeOutCubic'})
                    .belowTokens()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.99')
                    .atLocation(positions[e])
                    .rotateTowards(token)
                    .delay(800)
                    .size(token.width * token.texture.scaleX * 1.5, {gridUnits: true})
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteOffset({x: -1.15}, {gridUnits: true})
                    .spriteRotation(-90)
                .effect()
                    .copySprite(token)
                    .name('Disengage')
                    .atLocation(token)
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .duration(1500)
                    .fadeOut(0)
                    .scale(token.texture.scaleX)
                    .animateProperty('sprite', 'position.y', {from: 0, to: -0.25, duration: 300, gridUnits: true, ease: 'linear'})
                    .animateProperty('sprite', 'position.y', {from: 0, to: 0.25, duration: 500, gridUnits: true, delay: 300, ease: 'linear'})
                    .animateProperty('sprite', 'rotation', {from: 0, to: 360, duration: 600, ease: 'easeOutCirc'})
                    .waitUntilFinished(-300)
                .effect()
                    .copySprite(token)
                    .scale(token.texture.scaleX)
                    .atLocation(positions[e])
                    .duration(500)
                    .opacity(1)
                    .playIf(positions.length > 1)
                .effect()
                    .delay(200)
                    .copySprite(token)
                    .scale(token.texture.scaleX)
                    .atLocation(positions[e])
                    .fadeOut(500, {ease:'easeOutQuad'})
                    .duration(1000)
                    .opacity(1)
                    .playIf(positions.length == 1)
                .animation()
                    .delay(200)
                    .on(token)
                    .teleportTo(positions[e])
                    .snapToGrid()
                    .opacity(1)
                    .playIf(positions.length == 1)
                .play();
            /* eslint-enable indent */
            if (positions.length === 1) await token.actor.sheet.maximize();
        } else if (e == positions.length - 1) {
            /* eslint-disable indent */
            await new Sequence()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.43')
                    .atLocation(positions[e - 1])
                    .rotateTowards(positions[e])
                    .size(token.width * 1.75, {gridUnits: true})
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x: -1}, {gridUnits: true})
                    .randomRotation()
                .effect()
                    .copySprite(token)
                    .name('Disengage')
                    .atLocation(positions[e - 1])
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .duration(400)
                    .fadeIn(400, {ease: 'easeOutCirc'})
                    .fadeOut(0)
                    .scale(token.texture.scaleX)
                    .waitUntilFinished(-300)
                .effect()
                    .delay(200)
                    .copySprite(token)
                    .scale(token.texture.scaleX)
                    .atLocation(positions[e])
                    .fadeOut(500, {ease: 'easeOutQuad'})
                    .duration(1000)
                    .opacity(1)
                .animation()
                    .delay(200)
                    .on(token)
                    .teleportTo(positions[e])
                    .snapToGrid()
                    .opacity(1)
                .play();
            /* eslint-enable indent */
            await token.actor.sheet.maximize();
        } else {
            /* eslint-disable indent */
            await new Sequence()
                .effect()
                    .file('animated-spell-effects-cartoon.smoke.43')
                    .atLocation(positions[e - 1])
                    .rotateTowards(positions[e])
                    .size(token.width * 1.75, {gridUnits: true})
                    .belowTokens()
                    .opacity(0.65)
                    .scaleIn(0, 300, {ease: 'easeOutExpo'})
                    .filter('ColorMatrix', {saturate: -1, brightness: 0})
                    .spriteRotation(-90)
                    .spriteOffset({x: -1}, {gridUnits: true})
                    .randomRotation()
                .effect()
                    .copySprite(token)
                    .name('Disengage')
                    .atLocation(positions[e - 1])
                    .moveTowards(positions[e], {rotate: false, ease: 'easeOutCirc'})
                    .moveSpeed(1500)
                    .duration(400)
                    .fadeIn(400, {ease:'easeOutCirc'})
                    .fadeOut(0)
                    .filter('ColorMatrix', {saturate: -0.25, brightness: 0.65})
                    .scale(token.texture.scaleX)
                    .waitUntilFinished(-300)
                .play();
            /* eslint-enable indent */
        } 
    }
}
export const cunningActionDisengage = {
    name: 'CHRISPREMADES.Animations.CunningActionDisengage.Name',
    macros: {
        move
    },
    inputs: ['token', 'positions'],
    requirements: ['jb2a_patreon', 'animated-spell-effects-cartoon'],
    type: 'classFeature',
    get credits() {
        return [animationUtils.getEskieCredits()];
    }
};