const frenzyName = 'Moon Frenzy';
async function transform(token, {callback} = {}) {
    const gridSize = token.parent.grid.size;
    const scale = token.texture.scaleX;
    const shrinkWidth = {from: 1, to: 0.06 * gridSize, duration: 500, gridUnits: false, ease: 'easeInOutBack'};
    const shrinkHeight = {from: 1, to: 0.06 * gridSize, duration: 750, gridUnits: false, ease: 'easeOutBack'};
    const jitter = {from: -0.005, to: 0.005, duration: 100, pingPong: true, gridUnits: true};
    /* eslint-disable indent */
    await new Sequence()
        .effect()
            .file('jb2a.extras.tmfx.outflow.circle.01')
            .attachTo(token)
            .duration(5000)
            .fadeIn(500)
            .scaleIn(0, 750, {ease: 'easeOutSine'})
            .fadeOut(500)
            .scaleToObject(1.5)
            .randomRotation()
            .filter('ColorMatrix', {saturate: 0, brightness: 0})
            .animateProperty('sprite', 'scale.x', {from: 0, to: 0.25 * scale, duration: 500, gridUnits: true, ease: 'easeOutCubic', delay: 2600})
            .animateProperty('sprite', 'scale.y', {from: 0, to: 0.25 * scale, duration: 500, gridUnits: true, ease: 'easeOutCubic', delay: 2600})
            .belowTokens()
        .effect()
            .delay(400)
            .file('jb2a.template_circle.vortex.loop.dark_black')
            .attachTo(token)
            .duration(4000)
            .fadeIn(500)
            .scaleIn(0, 2400, {ease: 'easeOutSine'})
            .fadeOut(500)
            .scaleToObject(1.55, {considerTokenScale: true})
            .randomRotation()
            .filter('ColorMatrix', {saturate: 0, brightness: 0})
            .belowTokens()
        .effect()
            .copySprite(token)
            .attachTo(token)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.65)
            .repeats(3, 800, 800)
        .effect()
            .delay(3000)
            .file('jb2a.eyes.01.dark_red.single')
            .duration(1250)
            .attachTo(token)
            .scaleToObject(1.15)
            .fadeOut(500)
            .zIndex(1)
        .effect()
            .copySprite(token)
            .delay(2400)
            .attachTo(token)
            .duration(2000)
            .fadeIn(750)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(1)
            .filter('ColorMatrix', {brightness: 0})
            .filter('Blur', {blurX: 5, blurY: 5})
            .zIndex(0)
            .waitUntilFinished(-500)
        .thenDo(callback)
        .effect()
            .file('jb2a.claws.200px.dark_red')
            .atLocation(token)
            .scaleToObject(2.15)
            .fadeOut(500)
            .playbackRate(1.5)
            .belowTokens()
            .zIndex(1)
        .effect()
            .file('jb2a.impact.004.dark_red')
            .atLocation(token)
            .scaleToObject(2.75)
            .belowTokens()
            .fadeOut(500)
            .filter('ColorMatrix', {brightness: 0})
            .opacity(0.85)
        .play();
    /* eslint-enable indent */
}
async function moonFrenzyTransform(token, {callback, tintMap = false, moonColor = true} = {}) {
    const tintColor = moonColor ? '#d53333' : '#ffffff';
    const scene = token.parent;
    const gridSize = scene.grid.size;
    const scale = token.texture.scaleX;
    const shrinkWidth = {from: 1, to: 0.06 * gridSize, duration: 500, gridUnits: false, ease: 'easeInOutBack'};
    const shrinkHeight = {from: 1, to: 0.06 * gridSize, duration: 750, gridUnits: false, ease: 'easeOutBack'};
    const jitter = {from: -0.005, to: 0.005, duration: 100, pingPong: true, gridUnits: true};
    const mapLocation = {x: scene.dimensions.width / 2, y: scene.dimensions.height / 2};
    const mapSize = {width: scene.width / gridSize, height: scene.height / gridSize};
    /* eslint-disable indent */
    new Sequence()
        .effect()
            .delay(500)
            .atLocation(token)
            .file('jb2a.celestial_bodies.planet.no_atmo.03.grey')
            .belowTokens()
            .size(3, {gridUnits: true})
            .loopOptions({loops: 1})
            .startTime(13000)
            .duration(13000)
            .opacity(0.275)
            .filter('ColorMatrix', {saturate: -0.25, contrast: 0})
            .tint(tintColor)
            .fadeIn(1500)
            .fadeOut(3000)
            .zIndex(0.1)
        .effect()
            .atLocation(token)
            .file('jb2a.moonbeam.01.complete.yellow')
            .belowTokens()
            .duration(13000)
            .size(4.125, {gridUnits: true})
            .filter('ColorMatrix', {saturate: -0.5})
            .tint(tintColor)
            .opacity(0.1)
        .effect()
            .delay(500)
            .atLocation(token)
            .file('jb2a.extras.tmfx.inflow.circle.01')
            .belowTokens()
            .size(3, {gridUnits: true})
            .tint(tintColor)
            .opacity(0.2)
            .duration(13000)
            .fadeIn(1500)
            .fadeOut(3000)
            .zIndex(0.2)
        .play();
    await new Sequence()
        .wait(3000)
        .effect()
            .file('jb2a.extras.tmfx.outflow.circle.01')
            .atLocation(token)
            .duration(5000)
            .fadeIn(500)
            .scaleIn(0, 750, {ease: 'easeOutSine'})
            .fadeOut(500)
            .scaleToObject(1.5)
            .randomRotation()
            .filter('ColorMatrix', {saturate: 0, brightness: 0})
            .animateProperty('sprite', 'scale.x', {from: 0, to: token.width * 0.25 * scale, duration: 500, gridUnits: true, ease: 'easeOutCubic', delay: 2600})
            .animateProperty('sprite', 'scale.y', {from: 0, to: token.width * 0.25 * scale, duration: 500, gridUnits: true, ease: 'easeOutCubic', delay: 2600})
            .belowTokens()
        .effect()
            .copySprite(token)
            .attachTo(token)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.65)
            .repeats(3, 1200, 1200)
        .effect()
            .delay(100)
            .file(scene.firstLevel.background.src)
            .atLocation(mapLocation)
            .size(mapSize, {gridUnits: true})
            .spriteOffset({x: 0}, {gridUnits: true})
            .duration(1200)
            .fadeIn(200)
            .fadeOut(800, {ease: 'easeOutCubic'})
            .belowTokens()
            .opacity(0.8)
            .tint('#d53333')
            .filter('ColorMatrix', {saturate: -0.25, contrast: -0.2, brightness: 2})
            .repeats(3, 1200, 1200)
            .playIf(tintMap)
        .effect()
            .file(token.texture.src)
            .attachTo(token)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.25)
            .filter('ColorMatrix', {brightness: 0.75})
        .canvasPan()
        .shake({duration: 100, strength: 4, rotation: false})
        .effect()
            .file(token.texture.src)
            .delay(1200)
            .attachTo(token)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.5)
            .filter('ColorMatrix', {brightness: 0.5})
        .canvasPan()
            .delay(1200)
        .shake({duration: 100, strength: 4, rotation: false})
        .effect()
            .file(token.texture.src)
            .delay(2400)
            .attachTo(token)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.75)
            .filter('ColorMatrix', {brightness: 0.25})
        .canvasPan()
            .delay(2400)
        .shake({duration: 100, strength: 4, rotation: false})
        .effect()
            .delay(4200)
            .file('jb2a.eyes.01.dark_red.single')
            .duration(1250)
            .atLocation(token)
            .scaleToObject(1.15)
            .fadeOut(500)
            .zIndex(1)
        .effect()
            .file(token.texture.src)
            .delay(3600)
            .attachTo(token)
            .duration(2000)
            .fadeIn(500)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(0.75)
            .filter('ColorMatrix', {brightness: 0.2})
        .canvasPan()
            .delay(3600)
        .shake({duration: 100, strength: 4, rotation: false})
        .effect()
            .delay(3600)
            .file(scene.firstLevel.background.src)
            .atLocation(mapLocation)
            .size(mapSize, {gridUnits: true})
            .spriteOffset({x: 0}, {gridUnits: true})
            .duration(6000)
            .fadeIn(250)
            .fadeOut(500, {ease: 'easeOutCubic'})
            .belowTokens()
            .opacity(0.8)
            .tint('#d53333')
            .filter('ColorMatrix', {saturate: -0.25, contrast: -0.2, brightness: 2})
            .playIf(tintMap)
        .effect()
            .delay(3600)
            .file('jb2a.template_circle.vortex.loop.dark_black')
            .atLocation(token)
            .duration(2500)
            .fadeIn(500)
            .scaleIn(0, 750, {ease: 'easeOutSine'})
            .fadeOut(500)
            .scaleToObject(1.55, {considerTokenScale: true})
            .randomRotation()
            .filter('ColorMatrix', {saturate: 0, brightness: 0})
            .belowTokens()
        .animation()
            .delay(3600)
            .on(token)
            .opacity(0)
        .effect()
            .name(frenzyName)
            .file('jb2a.token_border.circle.static.orange.012')
            .delay(3600)
            .attachTo(token)
            .fadeIn(1000)
            .fadeOut(500)
            .scaleToObject(1.5)
            .filter('ColorMatrix', {saturate: 1})
            .tint('#FF0000')
            .belowTokens()
            .persist()
            .opacity(1)
            .zIndex(0)
        .effect()
            .copySprite(token)
            .delay(3600)
            .atLocation(token)
            .duration(2500)
            .fadeIn(350)
            .fadeOut(500)
            .scaleToObject(scale)
            .animateProperty('sprite', 'width', shrinkWidth)
            .animateProperty('sprite', 'height', shrinkHeight)
            .loopProperty('sprite', 'position.x', jitter)
            .opacity(1)
            .filter('ColorMatrix', {brightness: 0})
            .filter('Blur', {blurX: 5, blurY: 5})
            .zIndex(0)
            .waitUntilFinished(-1000)
        .thenDo(callback)
        .canvasPan()
        .shake({duration: 4500, fadeOutDuration: 500, strength: 2, rotation: false})
        .wait(250)
        .animation()
            .on(token)
            .opacity(1)
        .wait(250)
        .effect()
            .file('jb2a.claws.200px.dark_red')
            .atLocation(token)
            .scaleToObject(2.25)
            .fadeOut(500)
            .belowTokens()
            .zIndex(1)
        .effect()
            .file('jb2a.impact.004.dark_red')
            .atLocation(token)
            .scaleToObject(2.75)
            .belowTokens()
            .fadeOut(500)
            .filter('ColorMatrix', {brightness: 0})
            .opacity(0.85)
            .zIndex(0.9)
        .effect()
            .delay(450)
            .file('jb2a.impact.004.dark_red')
            .atLocation(token)
            .scaleToObject(2.75)
            .belowTokens()
            .fadeOut(750)
            .randomRotation()
            .filter('ColorMatrix', {brightness: 0})
            .opacity(0.45)
            .repeats(7, 450, 450)
            .zIndex(0.9)
        .effect()
            .file('jb2a.extras.tmfx.outpulse.circle.01.fast')
            .attachTo(token, {bindAlpha: false})
            .size(10, {gridUnits: true})
            .opacity(0.75)
            .filter('ColorMatrix', {saturate: -1, brightness: 0})
            .loopProperty('sprite', 'position.x', {from: 0.01, to: -0.01, gridUnits: true, pingPong: true, duration: 50})
            .belowTokens()
            .repeats(8, 450, 450)
            .fadeOut(1000)
            .zIndex(0)
        .play();
    /* eslint-enable indent */
}
async function endFrenzy(effect, token) {
    await Sequencer.EffectManager.endEffects({name: frenzyName, object: token});
}
export const shapeChange = {
    name: 'CHRISPREMADES.Animations.ShapeChange',
    macros: {
        transform
    },
    inputs: ['token', 'options'],
    requirements: ['jb2a_patreon'],
    category: 'feature'
};
export const moonFrenzy = {
    name: 'CHRISPREMADES.Animations.MoonFrenzy',
    macros: {
        transform: moonFrenzyTransform,
        delete: endFrenzy
    },
    inputs: ['token', 'options'],
    requirements: ['jb2a_patreon'],
    category: 'feature',
    config: {
        moonColor: {
            label: 'CHRISPREMADES.Config.MoonColor',
            type: 'checkbox',
            default: true
        },
        tintMap: {
            label: 'CHRISPREMADES.Config.TintMap',
            type: 'checkbox',
            default: false
        }
    }
};
