import {animationUtils} from '../../../proxy.mjs';
async function playDetailed(sourceToken, targetToken, missed) {
    const strikeDuration = missed ? 3000 : 6000;
    /* eslint-disable indent */
    new Sequence()
        .effect()
            .file('jb2a.ward.star.yellow.02')
            .atLocation(sourceToken)
            .scale(0.25)
            .duration(3000)
            .fadeIn(1000)
            .fadeOut(500)
        .effect()
            .file('jb2a.ward.star.yellow.02')
            .atLocation(sourceToken)
            .scale(0.25)
            .fadeIn(500)
            .fadeOut(500)
            .duration(1000)
        .effect()
            .file('jb2a.particles.outward.orange.01.03')
            .scaleIn(0.25, 500, {ease: 'easeOutQuint'})
            .size(2, {gridUnits: true})
            .fadeIn(500)
            .atLocation(sourceToken)
            .duration(3500)
            .fadeOut(2500)
        .effect()
            .file('jb2a.extras.tmfx.border.circle.outpulse.01.fast')
            .atLocation(sourceToken)
            .size(1.5, {gridUnits: true})
        .effect()
            .file('jb2a.glint.blue.few.0')
            .attachTo(sourceToken)
            .scaleToObject(1.75)
            .duration(strikeDuration)
            .fadeOut(500)
        .effect()
            .file('jb2a.token_border.circle.spinning.blue.001')
            .attachTo(sourceToken)
            .fadeIn(200)
            .fadeOut(500)
            .duration(750)
            .zIndex(1)
            .scaleToObject(2)
        .effect()
            .file('jb2a.token_border.circle.spinning.orange.001')
            .attachTo(sourceToken)
            .fadeIn(700)
            .scaleToObject(2)
            .playbackRate(5)
            .scaleOut(0, 250)
            .opacity(0.9)
            .duration(strikeDuration)
        .wait(1000)
        .effect()
            .file('jb2a.impact.002.yellow')
            .atLocation(sourceToken)
            .scaleToObject(2)
            .delay(1250)
            .playIf(!missed)
        .wait(1000)
        .effect()
            .file('jb2a.wind_stream.white')
            .atLocation(sourceToken)
            .rotateTowards(targetToken)
            .rotate(-180)
            .anchor({x: 0.5})
            .size(1, {gridUnits: true})
            .opacity(1)
            .duration(1500)
            .loopProperty('sprite', 'position.x', {from: -5, to: 5, duration: 50, pingPong: true})
            .fadeOut(3000)
            .zIndex(1)
            .playIf(!missed)
        .effect()
            .file('jb2a.extras.tmfx.border.circle.outpulse.01.fast')
            .atLocation(sourceToken)
            .anchor({x: 0.25})
            .rotateTowards(targetToken)
            .animateProperty('sprite', 'scale.y', {from: 0.5, to: 1, duration: 50, pingPong: false})
            .animateProperty('spriteContainer', 'position.x', {from: 0, to: -500, duration: 5000})
            .scaleToObject()
            .playIf(!missed)
        .effect()
            .file('jb2a.extras.tmfx.border.circle.outpulse.01.fast')
            .atLocation(sourceToken)
            .rotateTowards(targetToken)
            .anchor({x: -0.25})
            .scaleToObject(0.75)
            .animateProperty('sprite', 'scale.y', {from: 0.25, to: 0.75, duration: 50, pingPong: false})
            .animateProperty('spriteContainer', 'position.x', {from: 0, to: -500, duration: 5000})
            .delay(25)
            .playIf(!missed)
        .effect()
            .file('jb2a.extras.tmfx.border.circle.outpulse.01.fast')
            .atLocation(sourceToken)
            .anchor({x: -1.25})
            .rotateTowards(targetToken)
            .animateProperty('sprite', 'scale.y', {from: 0.25, to: 0.5, duration: 50, pingPong: false})
            .animateProperty('spriteContainer', 'position.x', {from: 0, to: -500, duration: 5000})
            .scaleToObject(0.5)
            .delay(40)
            .playIf(!missed)
        .effect()
            .file('modules/animated-spell-effects-cartoon/spell-effects/cartoon/magic/mind_sliver_LINE.webm')
            .atLocation(targetToken)
            .anchor({x: 0.75})
            .scale(0.075)
            .rotateTowards(sourceToken)
            .delay(10)
            .rotate(180)
            .zIndex(2)
            .playIf(!missed && !!animationUtils.aseCheck())
        .effect()
            .file('jb2a.impact.ground_crack.orange.02')
            .atLocation(targetToken)
            .scaleToObject(0.7)
            .fadeOut(5000)
            .delay(10)
            .zIndex(1)
            .playIf(!missed)
        .effect()
            .file('jb2a.impact.yellow.2')
            .atLocation(targetToken)
            .scaleToObject(3)
            .zIndex(2)
            .playIf(!missed)
            .waitUntilFinished(-2000)
        .effect()
            .file('jb2a.ground_cracks.orange.02')
            .atLocation(targetToken)
            .scaleToObject(0.7)
            .delay(10)
            .fadeOut(1000)
            .duration(4000)
            .zIndex(0)
            .playIf(!missed)
        .effect()
            .file('jb2a.particles.outward.orange.01.03')
            .scaleIn(0.25, 500, {ease: 'easeOutQuint'})
            .fadeIn(250)
            .rotateTowards(sourceToken)
            .fadeOut(500)
            .scaleToObject(1.5)
            .atLocation(targetToken)
            .animateProperty('spriteContainer', 'position.x', {from: -250, to: -1000, duration: 5000})
            .duration(2000)
            .playIf(!missed)
        .effect()
            .file('jb2a.glint.blue.many.0')
            .attachTo(targetToken)
            .randomRotation()
            .scaleToObject(0.75)
            .fadeIn(1000)
            .fadeOut(1000)
            .playIf(!missed)
        .play();
    /* eslint-enable indent */
}
async function attack(sourceToken, targetToken, {missed} = {}) {
    if (animationUtils.jb2aCheck() === 'patreon') return playDetailed(sourceToken, targetToken, missed);
    if (missed) return;
    /* eslint-disable indent */
    new Sequence()
        .effect()
            .file('jb2a.divine_smite.target.blueyellow')
            .atLocation(targetToken)
            .scaleToObject(2)
        .play();
    /* eslint-enable indent */
}
export const trueStrike = {
    name: 'CHRISPREMADES.Animations.TrueStrike',
    macros: {
        attack
    },
    inputs: ['sourceToken', 'targetToken', 'options'],
    requirements: ['JB2A_DnD5e'],
    category: 'spell',
    get credits() { return [animationUtils.getCredits('eskie')]; }
};
