// Spells
export {acidArrow} from './macros/2014/spells/acidArrow.js';
export {animateDead} from './macros/2014/spells/animateDead.js';
export {antagonize} from './macros/2014/spells/antagonize.js';
export {armorOfAgathys, armorOfAgathysArmor} from './macros/2014/spells/armorOfAgathys.js';
export {armsOfHadar} from './macros/2014/spells/armsOfHadar.js';
export {auraOfLife, auraOfLifeAura} from './macros/2014/spells/auraOfLife.js';
export {auraOfPurity, auraOfPurityAura} from './macros/2014/spells/auraOfPurity.js';
export {auraOfVitality} from './macros/2014/spells/auraOfVitality.js';
export {banishment, banishmentBanished} from './macros/2014/spells/banishment.js';
export {beaconOfHope, beaconOfHopeHopeful} from './macros/2014/spells/beaconOfHope.js';
export {bestowCurse, bestowCurseAttack, bestowCurseDamageSource, bestowCurseDamageTarget} from './macros/2014/spells/bestowCurse.js';
export {bigbysHand, bigbysHandItems} from './macros/2014/spells/bigbysHand.js';
export {bladeWard} from './macros/2014/spells/bladeWard.js';
export {bless} from './macros/2014/spells/bless.js';
export {blight, blightDamage} from './macros/2014/spells/blight.js';
export {blindingSmite, blindingSmiteDamage} from './macros/2014/spells/blindingSmite.js';
export {blink, blinkBlinking, blinkBlinkedAway} from './macros/2014/spells/blink.js';
export {boomingBlade, boomingBladeMoved} from './macros/2014/spells/boomingBlade.js';
export {borrowedKnowledge} from './macros/2014/spells/borrowedKnowledge.js';
export {brandingSmite, brandingSmiteDamage} from './macros/2014/spells/brandingSmite.js';
export {burningHands} from './macros/2014/spells/burningHands.js';
export {callLightning} from './macros/2014/spells/callLightning.js';
export {chainLightning} from './macros/2014/spells/chainLightning.js';
export {chaosBolt} from './macros/2014/spells/chaosBolt.js';
export {charmPerson} from './macros/2014/spells/charmPerson.js';
export {chillTouch, chillTouchChilled} from './macros/2014/spells/chillTouch.js';
export {chromaticOrb} from './macros/2014/spells/chromaticOrb.js';
export {cloudkill, cloudkillSource, cloudkillCloud} from './macros/2014/spells/cloudkill.js';
export {compelledDuel, compelledDuelSource, compelledDuelCompelled} from './macros/2014/spells/compelledDuel.js';
export {conjureAnimals} from './macros/2014/spells/conjureAnimals.js';
export {conjureCelestial} from './macros/2014/spells/conjureCelestial.js';
export {conjureElemental} from './macros/2014/spells/conjureElemental.js';
export {conjureFey} from './macros/2014/spells/conjureFey.js';
export {conjureMinorElementals} from './macros/2014/spells/conjureMinorElementals.js';
export {conjureWoodlandBeings} from './macros/2014/spells/conjureWoodlandBeings.js';
export {crownOfMadness} from './macros/2014/spells/crownOfMadness.js';
export {crownOfStars} from './macros/2014/spells/crownOfStars.js';
export {crusadersMantle, crusadersMantleAura} from './macros/2014/spells/crusadersMantle.js';
export {danseMacabre} from './macros/2014/spells/danseMacabre.js';
export {darkness} from './macros/2014/spells/darkness.js';
export {dawn, dawnShining} from './macros/2014/spells/dawn.js';
export {deathWard, deathWardWarded} from './macros/2014/spells/deathWard.js';
export {destructiveWave} from './macros/2014/spells/destructiveWave.js';
export {detectMagic, detectMagicDetecting} from './macros/2014/spells/detectMagic.js';
export {detectThoughts} from './macros/2014/spells/detectThoughts.js';
export {disintegrate} from './macros/2014/spells/disintegrate.js';
export {dragonsBreath} from './macros/2014/spells/dragonsBreath.js';
export {dustDevil, dustDevilEndTurn, dustDevilContact} from './macros/2014/spells/dustDevil.js';
export {earthTremor} from './macros/2014/spells/earthTremor.js';
export {eldritchBlast} from './macros/2014/spells/eldritchBlast.js';
export {elementalWeapon} from './macros/2014/spells/elementalWeapon.js';
export {enlargeReduce, enlargeReduceChanged} from './macros/2014/spells/enlargeReduce.js';
export {faerieFire, faerieFireOutlined} from './macros/2014/spells/faerieFire.js';
export {farStep, farStepStepping} from './macros/2014/spells/farStep.js';
export {findFamiliar, findFamiliarTouch} from './macros/2014/spells/findFamiliar.js';
export {findGreaterSteed, findGreaterSteedActive} from './macros/2014/spells/findGreaterSteed.js';
export {findSteed, findSteedActive} from './macros/2014/spells/findSteed.js';
export {fireShield, fireShieldShielded, fireShieldDismiss} from './macros/2014/spells/fireShield.js';
export {fireStorm} from './macros/2014/spells/fireStorm.js';
export {flameBlade} from './macros/2014/spells/flameBlade.js';
export {flamingSphere, flamingSphereEndTurn, flamingSphereRam} from './macros/2014/spells/flamingSphere.js';
export {flockOfFamiliars, flockOfFamiliarsTouch} from './macros/2014/spells/flockOfFamiliars.js';
export {fly, flyFlying} from './macros/2014/spells/fly.js';
export {fogCloud} from './macros/2014/spells/fogCloud.js';
export {frostFingers} from './macros/2014/spells/frostFingers.js';
export {gaseousForm} from './macros/2014/spells/gaseousForm.js';
export {globeOfInvulnerability, globeOfInvulnerabilityInvulnerable} from './macros/2014/spells/globeOfInvulnerability.js';
export {grease, greaseArea} from './macros/2014/spells/grease.js';
export {greenFlameBlade} from './macros/2014/spells/greenFlameBlade.js';
export {guardianOfFaith, guardianOfFaithDamage} from './macros/2014/spells/guardianOfFaith.js';
export {guardianOfNature} from './macros/2014/spells/guardianOfNature.js';
export {guidingBolt} from './macros/2014/spells/guidingBolt.js';
export {gustOfWind, gustOfWindGust} from './macros/2014/spells/gustOfWind.js';
export {hailOfThorns, hailOfThornsBurst} from './macros/2014/spells/hailOfThorns.js';
export {healingSpirit, healingSpiritHeal, healingSpiritSpirit} from './macros/2014/spells/healingSpirit.js';
export {heatMetal} from './macros/2014/spells/heatMetal.js';
export {heroism, heroismHeroic} from './macros/2014/spells/heroism.js';
export {hex, hexAttack} from './macros/2014/spells/hex.js';
export {holdPerson} from './macros/2014/spells/holdPerson.js';
export {holyWeapon} from './macros/2014/spells/holyWeapon.js';
export {hungerOfHadar, hungerOfHadarTemplate} from './macros/2014/spells/hungerOfHadar.js';
export {huntersMark, huntersMarkSource} from './macros/2014/spells/huntersMark.js';
export {hypnoticPattern, hypnoticPatternRemove} from './macros/2014/spells/hypnoticPattern.js';
export {iceStorm} from './macros/2014/spells/iceStorm.js';
export {insectPlague, insectPlagueTemplate} from './macros/2014/spells/insectPlague.js';
export {investitureOfFlame, investitureOfFlameFlaming} from './macros/2014/spells/investitureOfFlame.js';
export {investitureOfIce, investitureOfIceIcy} from './macros/2014/spells/investitureOfIce.js';
export {investitureOfStone} from './macros/2014/spells/investitureOfStone.js';
export {lifeTransference} from './macros/2014/spells/lifeTransference.js';
export {lightningArrow, lightningArrowBuffed} from './macros/2014/spells/lightningArrow.js';
export {lightningLure} from './macros/2014/spells/lightningLure.js';
export {magicMissile} from './macros/2014/spells/magicMissile.js';
export {massCureWounds} from './macros/2014/spells/massCureWounds.js';
export {maximiliansEarthenGrasp} from './macros/2014/spells/maximiliansEarthenGrasp.js';
export {mindSliver} from './macros/2014/spells/mindSliver.js';
export {mirrorImage, mirrorImageMirrored} from './macros/2014/spells/mirrorImage.js';
export {mistyStep} from './macros/2014/spells/mistyStep.js';
export {moonbeam, moonbeamBeam} from './macros/2014/spells/moonbeam.js';
export {passWithoutTrace, passWithoutTraceAura} from './macros/2014/spells/passWithoutTrace.js';
export {protectionFromEvilAndGood} from './macros/2014/spells/protectionFromEvilAndGood.js';
export {raulothimsPsychicLance} from './macros/2014/spells/raulothimsPsychicLance.js';
export {rayOfEnfeeblement, rayOfEnfeeblementEnfeebled} from './macros/2014/spells/rayOfEnfeeblement.js';
export {rimesBindingIce, rimesBindingIceFrozen} from './macros/2014/spells/rimesBindingIce.js';
export {sanctuary, sanctuarySafe} from './macros/2014/spells/sanctuary.js';
export {sappingSting} from './macros/2014/spells/sappingSting.js';
export {scorchingRay} from './macros/2014/spells/scorchingRay.js';
export {searingSmite, searingSmiteDamage} from './macros/2014/spells/searingSmite.js';
export {shadowBlade} from './macros/2014/spells/shadowBlade.js';
export {shadowOfMoil, shadowOfMoilBuffed} from './macros/2014/spells/shadowOfMoil.js';
export {shieldOfFaith} from './macros/2014/spells/shieldOfFaith.js';
export {shield} from './macros/2014/spells/shield.js';
export {shockingGrasp} from './macros/2014/spells/shockingGrasp.js';
export {sickeningRadiance, sickeningRadianceTemplate, sickeningRadianceSickened} from './macros/2014/spells/sickeningRadiance.js';
export {skillEmpowerment} from './macros/2014/spells/skillEmpowerment.js';
export {sleetStorm, sleetStormArea} from './macros/2014/spells/sleetStorm.js';
export {spikeGrowth, spikeGrowthSpikes} from './macros/2014/spells/spikeGrowth.js';
export {spiritGuardians, spiritGuardiansDamage} from './macros/2014/spells/spiritGuardians.js';
export {spiritOfDeath, spiritOfDeathReapingScythe, spiritOfDeathHauntCreature, spiritOfDeathHauntCreatureHaunt} from './macros/2014/spells/spiritOfDeath.js';
export {spiritShroud, spiritShroudShrouded} from './macros/2014/spells/spiritShroud.js';
export {spiritualWeapon} from './macros/2014/spells/spiritualWeapon.js';
export {sprayOfCards} from './macros/2014/spells/sprayOfCards.js';
export {staggeringSmite, staggeringSmiteDamage} from './macros/2014/spells/staggeringSmite.js';
export {stormSphere, stormSphereTemplate} from './macros/2014/spells/stormSphere.js';
export {summonAberration, summonAberrationWhisperingAura} from './macros/2014/spells/summonAberration.js';
export {summonBeast} from './macros/2014/spells/summonBeast.js';
export {summonCelestial, summonCelestialMace} from './macros/2014/spells/summonCelestial.js';
export {summonConstruct, summonConstructStone} from './macros/2014/spells/summonConstruct.js';
export {summonDraconicSpirit, summonDraconicSpiritBreathWeapon} from './macros/2014/spells/summonDraconicSpirit.js';
export {summonElemental} from './macros/2014/spells/summonElemental.js';
export {summonFey, summonFeyFeyStep} from './macros/2014/spells/summonFey.js';
export {summonFiend, summonFiendClaws, summonFiendDeathThroes} from './macros/2014/spells/summonFiend.js';
export {summonLesserDemons} from './macros/2014/spells/summonLesserDemons.js';
export {summonShadowspawn, summonShadowspawnDespair} from './macros/2014/spells/summonShadowspawn.js';
export {summonUndead, summonUndeadPutrid} from './macros/2014/spells/summonUndead.js';
export {synapticStatic} from './macros/2014/spells/synapticStatic.js';
export {tashasCausticBrew} from './macros/2014/spells/tashasCausticBrew.js';
export {tashasOtherworldlyGuise, tashasOtherworldlyGuiseBuffed} from './macros/2014/spells/tashasOtherworldlyGuise.js';
export {teleport} from './macros/2014/spells/teleport.js';
export {thornWhip} from './macros/2014/spells/thornWhip.js';
export {thunderStep} from './macros/2014/spells/thunderStep.js';
export {thunderousSmite, thunderousSmiteDamage} from './macros/2014/spells/thunderousSmite.js';
export {thunderwave} from './macros/2014/spells/thunderwave.js';
export {tidalWave} from './macros/2014/spells/tidalWave.js';
export {tollTheDead} from './macros/2014/spells/tollTheDead.js';
export {vampiricTouch} from './macros/2014/spells/vampiricTouch.js';
export {vitriolicSphere} from './macros/2014/spells/vitriolicSphere.js';
export {vortexWarp} from './macros/2014/spells/vortexWarp.js';
export {wallOfFire, wallOfFireWallRegion, wallOfFireRegion} from './macros/2014/spells/wallOfFire.js';
export {wardingBond, wardingBondTarget, wardingBondSource} from './macros/2014/spells/wardingBond.js';
export {witherAndBloom} from './macros/2014/spells/witherAndBloom.js';
export {wrathfulSmite, wrathfulSmiteDamage} from './macros/2014/spells/wrathfulSmite.js';
export {zoneOfTruth} from './macros/2014/spells/zoneOfTruth.js';
// Other
export {actionDismissal} from './macros/2014/generic/actionDismissal.js';
export {noConfiguration} from './macros/2014/generic/noConfiguration.js';
export {noReactions} from './macros/2014/generic/noReactions.js';
export {proneOnFail} from './macros/2014/generic/proneOnFail.js';
export {proneOnHit} from './macros/2014/generic/proneOnHit.js';
export {removeOnMiss} from './macros/2014/generic/removeOnMiss.js';
export {removeTemplate} from './macros/2014/generic/removeTemplate.js';
export {setAttackRoll} from './macros/2014/generic/setAttackRoll.js';
export {setDamageRoll} from './macros/2014/generic/setDamageRoll.js';
export {spotlightOmniSearchSummon} from './integrations/spotlightOmnisearch.js';
export {summonTurnHostile} from './macros/2014/generic/summonTurnHostile.js';
export {summonUtils} from './lib/summons.js';
export {test, test2} from './macros/test.js';
export {useOnDeath} from './macros/2014/generic/useOnDeath.js';
// Class Features
export {adeptMarksman} from './macros/2014/classFeatures/fighter/gunslinger/adeptMarksman.js';
export {agonizingBlast} from './macros/2014/classFeatures/warlock/invocations/agonizingBlast.js';
export {alchemicalSavant} from './macros/2014/classFeatures/artificer/alchemist/alchemicalSavant.js';
export {ancestralProtectors, ancestralProtectorsTarget} from './macros/2014/classFeatures/barbarian/ancestralGuardian/ancestralProtectors.js';
export {animatingPerformance, animatingPerformanceDance} from './macros/2014/classFeatures/bard/collegeOfCreation/animatingPerformance.js';
export {arcaneAbjuration} from './macros/2014/classFeatures/cleric/arcanaDomain/arcaneAbjuration.js';
export {arcaneJolt} from './macros/2014/classFeatures/artificer/battleSmith/arcaneJolt.js';
export {arcaneWard} from './macros/2014/classFeatures/wizard/schoolOfAbjuration/arcaneWard.js';
export {armorModifications} from './macros/2014/classFeatures/artificer/armorer/armorModifications.js';
export {augmentBreath} from './macros/2014/classFeatures/monk/wayOfTheAscendantDragon/augmentBreath.js';
export {auraOfAlacrity} from './macros/2014/classFeatures/paladin/oathOfGlory/auraOfAlacrity.js';
export {auraOfClarity} from './macros/2014/classFeatures/paladin/oathOfZeal/auraOfClarity.js';
export {auraOfConquest, auraOfConquestAura} from './macros/2014/classFeatures/paladin/oathOfConquest/auraOfConquest.js';
export {auraOfCourage} from './macros/2014/classFeatures/paladin/auraOfCourage.js';
export {auraOfDevotion} from './macros/2014/classFeatures/paladin/oathOfDevotion/auraOfDevotion.js';
export {auraOfHate} from './macros/2014/classFeatures/paladin/oathbreaker/auraOfHate.js';
export {auraOfProtection} from './macros/2014/classFeatures/paladin/auraOfProtection.js';
export {auraOfWarding} from './macros/2014/classFeatures/paladin/oathOfTheAncients/auraOfWarding.js';
export {awakenedSpellbook} from './macros/2014/classFeatures/wizard/orderOfScribes/awakenedSpellbook.js';
export {balmOfPeace} from './macros/2014/classFeatures/cleric/peaceDomain/balmOfPeace.js';
export {balmOfTheSummerCourt} from './macros/2014/classFeatures/druid/circleOfDreams/balmOfTheSummerCourt.js';
export {bardicInspiration, bardicInspirationInspired} from './macros/2014/classFeatures/bard/bardicInspiration.js';
export {beguilingTwist} from './macros/2014/classFeatures/ranger/feyWanderer/beguilingTwist.js';
export {bestialSoul} from './macros/2014/classFeatures/barbarian/beast/bestialSoul.js';
export {bladeFlourish} from './macros/2014/classFeatures/bard/collegeOfSwords/bladeFlourish.js';
export {bladesong} from './macros/2014/classFeatures/wizard/bladeSinging/bladesong.js';
export {blessedHealer} from './macros/2014/classFeatures/cleric/lifeDomain/blessedHealer.js';
export {blessedStrikes} from './macros/2014/classFeatures/cleric/blessedStrikes.js';
export {blessingOfTheForge} from './macros/2014/classFeatures/cleric/forgeDomain/blessingOfTheForge.js';
export {bloodMaledict} from './macros/2014/classFeatures/bloodHunter/bloodMaledict.js';
export {bolsteringMagic} from './macros/2014/classFeatures/barbarian/wildMagic/bolsteringMagic.js';
export {brandOfCastigation, brandOfCastigationActive} from './macros/2014/classFeatures/bloodHunter/brandOfCastigation.js';
export {breathOfTheDragon} from './macros/2014/classFeatures/monk/wayOfTheAscendantDragon/breathOfTheDragon.js';
export {bullyingShot, dazingShot, deadeyeShot, disarmingShot, forcefulShot, piercingShotTrickshot, violentShot, wingingShot} from './macros/2014/classFeatures/fighter/gunslinger/trickShots.js';
export {callTheHunt} from './macros/2014/classFeatures/barbarian/beast/callTheHunt.js';
export {carefulSpell, distantSpell, empoweredSpell, extendedSpell, heightenedSpell, quickenedSpell, seekingSpell, subtleSpell, transmutedSpell, twinnedSpell, twinnedSpellAttack} from './macros/2014/classFeatures/sorcerer/metamagic.js';
export {charmAnimalsAndPlants} from './macros/2014/classFeatures/cleric/natureDomain/charmAnimalsAndPlants.js';
export {circleForms} from './macros/2014/classFeatures/druid/circleOfTheMoon/circleForms.js';
export {circleOfMortality} from './macros/2014/classFeatures/cleric/graveDomain/circleOfMortality.js';
export {colossusSlayer} from './macros/2014/classFeatures/ranger/hunter/colossusSlayer.js';
export {controlUndead, controlUndeadControlled} from './macros/2014/classFeatures/paladin/oathbreaker/controlUndead.js';
export {controlledSurge} from './macros/2014/classFeatures/barbarian/wildMagic/controlledSurge.js';
export {createMutagen} from './macros/2014/classFeatures/bloodHunter/orderOfTheMutant/createMutagen.js';
export {createPactWeapon} from './macros/2014/classFeatures/warlock/boons/pactOfTheBlade/createPactWeapon.js';
export {crimsonRite} from './macros/2014/classFeatures/bloodHunter/crimsonRite.js';
export {curseOfBinding} from './macros/2014/classFeatures/bloodHunter/bloodCurses/curseOfBinding.js';
export {curseOfTheFallenPuppet} from './macros/2014/classFeatures/bloodHunter/bloodCurses/curseOfTheFallenPuppet.js';
export {curseOfTheMuddledMind} from './macros/2014/classFeatures/bloodHunter/bloodCurses/curseOfTheMuddledMind.js';
export {dangerSense} from './macros/2014/classFeatures/barbarian/dangerSense.js';
export {darkOnesBlessing} from './macros/2014/classFeatures/warlock/fiend/darkOnesBlessing.js';
export {darkOnesOwnLuck} from './macros/2014/classFeatures/warlock/fiend/darkOnesOwnLuck.js';
export {demiurgicColossus} from './macros/2014/classFeatures/barbarian/giant/demiurgicColossus.js';
export {destructiveWrath, destructiveWrathActive} from './macros/2014/classFeatures/cleric/tempestDomain/destructiveWrath.js';
export {devilsSight} from './macros/2014/classFeatures/warlock/invocations/devilsSight.js';
export {discipleOfLife} from './macros/2014/classFeatures/cleric/lifeDomain/discipleOfLife.js';
export {divineFuryNecrotic, divineFuryRadiant} from './macros/2014/classFeatures/barbarian/zealot/divineFury.js';
export {divineSmite} from './macros/2014/classFeatures/paladin/divineSmite.js';
export {divineStrike} from './macros/2014/classFeatures/cleric/divineStrike.js';
export {draconicStrike} from './macros/2014/classFeatures/monk/wayOfTheAscendantDragon/draconicStrike.js';
export {dreadAmbusher} from './macros/2014/classFeatures/ranger/gloomStalker/dreadAmbusher.js';
export {dreadLord, dreadLordAura} from './macros/2014/classFeatures/paladin/oathbreaker/dreadLord.js';
export {dreadfulAspect, dreadfulAspectFrightened} from './macros/2014/classFeatures/paladin/oathbreaker/dreadfulAspect.js';
export {dreadfulStrikes} from './macros/2014/classFeatures/ranger/feyWanderer/dreadfulStrikes.js';
export {durableMagic} from './macros/2014/classFeatures/wizard/warMagic/durableMagic.js';
export {echoAvatar} from './macros/2014/classFeatures/fighter/echoKnight/echoAvatar.js';
export {eldritchCannon, eldritchCannonExplosiveCannon, eldritchCannonForceBallista, eldritchCannonFortifiedPosition} from './macros/2014/classFeatures/artificer/artillerist/eldritchCannon.js';
export {eldritchSmite} from './macros/2014/classFeatures/warlock/invocations/eldritchSmite.js';
export {elementalCleaver} from './macros/2014/classFeatures/barbarian/giant/elementalCleaver.js';
export {elementalGiftDao, elementalGiftDjinni, elementalGiftEfreeti, elementalGiftMarid} from './macros/2014/classFeatures/warlock/genie/elementalGift.js';
export {elementalWildShape} from './macros/2014/classFeatures/druid/circleOfTheMoon/elementalWildShape.js';
export {emboldeningBond, emboldeningBondEmboldened} from './macros/2014/classFeatures/cleric/peaceDomain/emboldeningBond.js';
export {empoweredEvocation} from './macros/2014/classFeatures/wizard/schoolOfEvocation/empoweredEvocation.js';
export {enhancedBond} from './macros/2014/classFeatures/druid/circleOfWildfire/enhancedBond.js';
export {evasion} from './macros/2014/classFeatures/multiple/evasion.js';
export {expansiveBond} from './macros/2014/classFeatures/cleric/peaceDomain/expansiveBond.js';
export {experimentalElixir, experimentalElixirConsumable} from './macros/2014/classFeatures/artificer/alchemist/experimentalElixir.js';
export {expertDivination} from './macros/2014/classFeatures/wizard/schoolOfDivination/expertDivination.js';
export {eyeForWeakness} from './macros/2014/classFeatures/rogue/inquisitive/eyeForWeakness.js';
export {eyesOfNight} from './macros/2014/classFeatures/cleric/twilightDomain/eyesOfNight.js';
export {favoredByTheGods} from './macros/2014/classFeatures/sorcerer/divineSoul/favoredByTheGods.js';
export {favoredFoe} from './macros/2014/classFeatures/ranger/favoredFoe.js';
export {feyPresence} from './macros/2014/classFeatures/warlock/archfey/feyPresence.js';
export {fightingSpirit} from './macros/2014/classFeatures/fighter/samurai/fightingSpirit.js';
export {fightingStyleSuperiorTechnique} from './macros/2014/classFeatures/multiple/fightingStyleSuperiorTechnique.js';
export {fightingStyleUnarmedFighting, fightingStyleUnarmedFightingUnarmedStrike} from './macros/2014/classFeatures/multiple/fightingStyleUnarmedFighting.js';
export {fireRune, frostRune, stoneRune, hillRune, stormRune, cloudRune} from './macros/2014/classFeatures/fighter/runeKnight/runes.js';
export {focusedAim} from './macros/2014/classFeatures/monk/focusedAim.js';
export {formOfDread, formOfDreadActive} from './macros/2014/classFeatures/warlock/undead/formOfDread.js';
export {formOfTheBeast} from './macros/2014/classFeatures/barbarian/beast/formOfTheBeast.js';
export {formulas, formulaAether, formulaAlluring, formulaCelerity, formulaConversant, formulaCruelty, formulaDeftness, formulaEmbers, formulaGelid, formulaImpermeable, formulaMobility, formulaNighteye, formulaPercipient, formulaPotency, formulaPrecision, formulaRapidity, formulaReconstruction, formulaSagacity, formulaShielded, formulaUnbreakable, formulaVermillion} from './macros/2014/classFeatures/bloodHunter/orderOfTheMutant/formulas.js';
export {geniesWrathDao, geniesWrathDjinni, geniesWrathEfreeti, geniesWrathMarid} from './macros/2014/classFeatures/warlock/genie/geniesWrath.js';
export {giantsHavocCrushingThrow} from './macros/2014/classFeatures/barbarian/giant/crushingThrow.js';
export {giantsHavocGiantStature} from './macros/2014/classFeatures/barbarian/giant/giantStature.js';
export {giantsMight, giantsMightEffect} from './macros/2014/classFeatures/fighter/runeKnight/giantsMight.js';
export {graspOfHadar} from './macros/2014/classFeatures/warlock/invocations/graspOfHadar.js';
export {graveTouched} from './macros/2014/classFeatures/warlock/undead/graveTouched.js';
export {greatStature} from './macros/2014/classFeatures/fighter/runeKnight/greatStature.js';
export {grimHarvest} from './macros/2014/classFeatures/wizard/schoolOfNecromancy/grimHarvest.js';
export {guardianArmor, guardianArmorThunderGauntlets} from './macros/2014/classFeatures/artificer/armorer/guardianArmor.js';
export {harnessDivinePower} from './macros/2014/classFeatures/cleric/harnessDivinePower.js';
export {healingLight} from './macros/2014/classFeatures/warlock/celestial/healingLight.js';
export {heartOfTheStorm} from './macros/2014/classFeatures/sorcerer/stormSorcery/heartOfTheStorm.js';
export {hearthOfMoonlightAndShadow} from './macros/2014/classFeatures/druid/circleOfDreams/hearthOfMoonlightAndShadow.js';
export {heightenedSenses} from './macros/2014/classFeatures/bloodHunter/orderOfTheLycan/heightenedSenses.js';
export {hemorrhagingCritical} from './macros/2014/classFeatures/fighter/gunslinger/hemorrhagingCritical.js';
export {hexWarrior} from './macros/2014/classFeatures/warlock/hexblade/hexWarrior.js';
export {hexbladesCurse, hexbladesCurseSource, hexbladesCurseTarget} from './macros/2014/classFeatures/warlock/hexblade/hexbladesCurse.js';
export {hiddenPaths} from './macros/2014/classFeatures/druid/circleOfDreams/hiddenPaths.js';
export {holyNimbus, holyNimbusActive} from './macros/2014/classFeatures/paladin/oathOfDevotion/holyNimbus.js';
export {homingStrikes} from './macros/2014/classFeatures/rogue/soulknife/homingStrikes.js';
export {hybridTransformation, hybridTransformationActive} from './macros/2014/classFeatures/bloodHunter/orderOfTheLycan/hybridTransformation.js';
export {improvedPactWeapon} from './macros/2014/classFeatures/warlock/invocations/improvedPactWeapon.js';
export {infectiousFury} from './macros/2014/classFeatures/barbarian/beast/infectiousFury.js';
export {infiltratorArmor, infiltratorArmorLightningLauncher} from './macros/2014/classFeatures/artificer/armorer/infiltratorArmor.js';
export {infuseItem, infuseItemArmorStrength, infuseItemHomunculusTouch, infuseItemRepulsionShield, infuseItemSpellRing} from './macros/2014/classFeatures/artificer/infuseItem.js';
export {insightfulFighting} from './macros/2014/classFeatures/rogue/inquisitive/insightfulFighting.js';
export {inspiringSmite} from './macros/2014/classFeatures/paladin/oathOfGlory/inspiringSmite.js';
export {investmentOfTheChainMaster, investmentOfTheChainMasterActive} from './macros/2014/classFeatures/warlock/invocations/investmentOfTheChainMaster.js';
export {ki} from './macros/2014/classFeatures/monk/ki.js';
export {lanceOfLethargy} from './macros/2014/classFeatures/warlock/invocations/lanceOfLethargy.js';
export {layOnHands} from './macros/2014/classFeatures/paladin/layOnHands.js';
export {legionOfOne} from './macros/2014/classFeatures/fighter/echoKnight/legionOfOne.js';
export {lightningReload} from './macros/2014/classFeatures/fighter/gunslinger/lightningReload.js';
export {maddeningHex} from './macros/2014/classFeatures/warlock/invocations/maddeningHex.js';
export {magicalInspiration} from './macros/2014/classFeatures/bard/magicalInspiration.js';
export {maneuversAmbush, maneuversBaitAndSwitch, maneuversBrace, maneuversCommandersStrike, maneuversCommandingPresence, maneuversDisarmingAttack, maneuversDistractingStrike, maneuversEvasiveFootwork, maneuversFeintingAttack, maneuversGoadingAttack, maneuversGrapplingStrike, maneuversLungingAttack, maneuversManeuveringAttack, maneuversMenacingAttack, maneuversParry, maneuversPrecisionAttack, maneuversPushingAttack, maneuversQuickToss, maneuversRally, maneuversRiposte, maneuversSweepingAttack, maneuversTacticalAssessment, maneuversTripAttack, distractingStrikeEffect} from './macros/2014/classFeatures/fighter/battleMaster/maneuvers.js';
export {manifestEcho, manifestEchoActive} from './macros/2014/classFeatures/fighter/echoKnight/manifestEcho.js';
export {manifestMind, manifestMindCast} from './macros/2014/classFeatures/wizard/orderOfScribes/manifestMind.js';
export {masterOfHexes} from './macros/2014/classFeatures/warlock/hexblade/masterOfHexes.js';
export {mastersFlourish} from './macros/2014/classFeatures/bard/collegeOfSwords/mastersFlourish.js';
export {mightyImpel} from './macros/2014/classFeatures/barbarian/giant/mightyImpel.js';
export {mightySummoner} from './macros/2014/classFeatures/druid/circleOfTheShepard/mightySummoner.js';
export {mistyEscape} from './macros/2014/classFeatures/warlock/archfey/mistyEscape.js';
export {monkUnarmedStrike} from './macros/2014/classFeatures/monk/unarmedStrike.js';
export {moteOfPotential} from './macros/2014/classFeatures/bard/collegeOfCreation/moteOfPotential.js';
export {naturesWrath} from './macros/2014/classFeatures/paladin/oathOfTheAncients/naturesWrath.js';
export {oneWithShadows} from './macros/2014/classFeatures/warlock/invocations/oneWithShadows.js';
export {overchannel} from './macros/2014/classFeatures/wizard/schoolOfEvocation/overchannel.js';
export {pathToTheGrave} from './macros/2014/classFeatures/cleric/graveDomain/pathToTheGrave.js';
export {patientDefense} from './macros/2014/classFeatures/monk/patientDefense.js';
export {peerlessAthlete} from './macros/2014/classFeatures/paladin/oathOfGlory/peerlessAthlete.js';
export {persistentRage} from './macros/2014/classFeatures/barbarian/persistentRage.js';
export {potentCantrip} from './macros/2014/classFeatures/wizard/schoolOfEvocation/potentCantrip.js';
export {potentSpellcasting} from './macros/2014/classFeatures/cleric/potentSpellcasting.js';
export {preserveLife} from './macros/2014/classFeatures/cleric/lifeDomain/preserveLife.js';
export {primalCompanion, primalCompanionSea} from './macros/2014/classFeatures/ranger/beastMaster/primalCompanion.js';
export {primalStrike} from './macros/2014/classFeatures/druid/circleOfTheMoon/primalStrike.js';
export {projectedWard} from './macros/2014/classFeatures/wizard/schoolOfAbjuration/projectedWard.js';
export {protectiveBond} from './macros/2014/classFeatures/cleric/peaceDomain/protectiveBond.js';
export {psionicEnergy} from './macros/2014/classFeatures/rogue/soulknife/psionicEnergy.js';
export {psionicPowerRecovery} from './macros/2014/classFeatures/rogue/soulknife/psionicPowerRecovery.js';
export {psionicSorcery} from './macros/2014/classFeatures/sorcerer/aberrantMind/psionicSorcery.js';
export {psionicSpells} from './macros/2014/classFeatures/sorcerer/aberrantMind/psionicSpells.js';
export {psychicBlades} from './macros/2014/classFeatures/rogue/soulknife/psychicBlades.js';
export {psychicDefenses} from './macros/2014/classFeatures/sorcerer/aberrantMind/psychicDefenses.js';
export {purityOfSpirit} from './macros/2014/classFeatures/paladin/oathOfDevotion/purityOfSpirit.js';
export {quickdraw} from './macros/2014/classFeatures/fighter/gunslinger/quickdraw.js';
export {quickenedHealing} from './macros/2014/classFeatures/monk/quickenedHealing.js';
export {radianceOfTheDawn} from './macros/2014/classFeatures/cleric/lightDomain/radianceOfTheDawn.js';
export {radiantSoul} from './macros/2014/classFeatures/warlock/celestial/radiantSoul.js';
export {rage, rageRaging} from './macros/2014/classFeatures/barbarian/rage.js';
export {rakishAudacity} from './macros/2014/classFeatures/rogue/swashbuckler/rakishAudacity.js';
export {rapidRepair} from './macros/2014/classFeatures/fighter/gunslinger/rapidRepair.js';
export {reaper} from './macros/2014/classFeatures/cleric/deathDomain/reaper.js';
export {reclaimPotential} from './macros/2014/classFeatures/fighter/echoKnight/reclaimPotential.js';
export {relentlessHex} from './macros/2014/classFeatures/warlock/invocations/relentlessHex.js';
export {relentless} from './macros/2014/classFeatures/fighter/battleMaster/relentless.js';
export {rendMind} from './macros/2014/classFeatures/rogue/soulknife/rendMind.js';
export {repellingBlast} from './macros/2014/classFeatures/warlock/invocations/repellingBlast.js';
export {revelationInFlesh} from './macros/2014/classFeatures/sorcerer/aberrantMind/revelationInFlesh.js';
export {riteOfTheDawn, riteOfTheDead, riteOfTheFlame, riteOfTheFrozen, riteOfTheOracle, riteOfTheRoar, riteOfTheStorm} from './macros/2014/classFeatures/bloodHunter/rites.js';
export {runicJuggernaut} from './macros/2014/classFeatures/fighter/runeKnight/runicJuggernaut.js';
export {runicShield} from './macros/2014/classFeatures/fighter/runeKnight/runicShield.js';
export {sacredWeapon} from './macros/2014/classFeatures/paladin/oathOfDevotion/sacredWeapon.js';
export {sculptSpells, sculptSpellsTarget} from './macros/2014/classFeatures/wizard/schoolOfEvocation/sculptSpells.js';
export {sentinelAtDeathsDoor} from './macros/2014/classFeatures/cleric/graveDomain/sentinelAtDeathsDoor.js';
export {shadowStep} from './macros/2014/classFeatures/monk/wayOfShadow/shadowStep.js';
export {sneakAttack} from './macros/2014/classFeatures/rogue/sneakAttack.js';
export {songOfDefense} from './macros/2014/classFeatures/wizard/bladeSinging/songOfDefense.js';
export {songOfVictory} from './macros/2014/classFeatures/wizard/bladeSinging/songOfVictory.js';
export {sorceryPoints} from './macros/2014/classFeatures/sorcerer/sorceryPoints.js';
export {spiritShield} from './macros/2014/classFeatures/barbarian/ancestralGuardian/spiritShield.js';
export {stalkersProwess} from './macros/2014/classFeatures/bloodHunter/orderOfTheLycan/stalkersProwess.js';
export {starryForm, starryFormActive} from './macros/2014/classFeatures/druid/circleOfStars/starryForm.js';
export {steelDefender, steelDefenderArcaneJolt, steelDefenderDeflectAttack, steelDefenderRepair} from './macros/2014/classFeatures/artificer/battleSmith/steelDefender.js';
export {stepsOfNight} from './macros/2014/classFeatures/cleric/twilightDomain/stepsOfNight.js';
export {stillnessOfMind} from './macros/2014/classFeatures/monk/stillnessOfMind.js';
export {strangeMetabolism} from './macros/2014/classFeatures/bloodHunter/orderOfTheMutant/strangeMetabolism.js';
export {strengthOfTheGrave} from './macros/2014/classFeatures/sorcerer/shadowMagic/strengthOfTheGrave.js';
export {stunningStrike} from './macros/2014/classFeatures/monk/stunningStrike.js';
export {summonDrakeCompanion, summonDrakeCompanionResistance, summonDrakeCompanionInfuse} from './macros/2014/classFeatures/ranger/drakewarden/summonDrakeCompanion.js';
export {summonWildfireSpirit, summonWildfireSpiritTeleport} from './macros/2014/classFeatures/druid/circleOfWildfire/summonWildfireSpirit.js';
export {superiorityDice} from './macros/2014/classFeatures/fighter/battleMaster/superiorityDice.js';
export {supremeHealing} from './macros/2014/classFeatures/cleric/lifeDomain/supremeHealing.js';
export {telepathicSpeech} from './macros/2014/classFeatures/sorcerer/aberrantMind/telepathicSpeech.js';
export {tentacleOfTheDeeps} from './macros/2014/classFeatures/warlock/fathomless/tentacleOfTheDeeps.js';
export {thunderboltStrike} from './macros/2014/classFeatures/cleric/tempestDomain/thunderboltStrike.js';
export {totemSpiritBear} from './macros/2014/classFeatures/barbarian/totem/totemSpirit.js';
export {turnTheFaithless} from './macros/2014/classFeatures/paladin/oathOfTheAncients/turnTheFaithless.js';
export {turnUndead} from './macros/2014/classFeatures/cleric/turnUndead.js';
export {twilightSanctuary, twilightSanctuaryActive} from './macros/2014/classFeatures/cleric/twilightDomain/twilightSanctuary.js';
export {twilightShroud, twilightShroudActive} from './macros/2014/classFeatures/cleric/twilightDomain/twilightShroud.js';
export {twinklingConstellations} from './macros/2014/classFeatures/druid/circleOfStars/twinklingConstellations.js';
export {umbralSight} from './macros/2014/classFeatures/ranger/gloomStalker/umbralSight.js';
export {unarmoredDefenseBarbarian} from './macros/2014/classFeatures/barbarian/unarmoredDefense.js';
export {unarmoredDefenseMonk} from './macros/2014/classFeatures/monk/unarmoredDefense.js';
export {undeadThralls} from './macros/2014/classFeatures/wizard/schoolOfNecromancy/undeadThralls.js';
export {unleashIncarnation} from './macros/2014/classFeatures/fighter/echoKnight/unleashIncarnation.js';
export {unstableBacklash} from './macros/2014/classFeatures/barbarian/wildMagic/unstableBacklash.js';
export {vengefulAncestors} from './macros/2014/classFeatures/barbarian/ancestralGuardian/vengefulAncestors.js';
export {viciousIntent} from './macros/2014/classFeatures/fighter/gunslinger/viciousIntent.js';
export {vigilantBlessing} from './macros/2014/classFeatures/cleric/twilightDomain/vigilantBlessing.js';
export {warpingImplosion} from './macros/2014/classFeatures/sorcerer/aberrantMind/warpingImplosion.js';
export {wildShape, wildShapeActive} from './macros/2014/classFeatures/druid/wildShape.js';
export {wildSurge, wildSurgeIntangibleSpirit, wildSurgeProtectiveLights, wildSurgeRetribution, wildSurgeTeleport} from './macros/2014/classFeatures/barbarian/wildMagic/wildSurge.js';
export {wrathOfTheStorm} from './macros/2014/classFeatures/cleric/tempestDomain/wrathOfTheStorm.js';
export {zealousPresence} from './macros/2014/classFeatures/barbarian/zealot/zealousPresence.js';
export {balefulInterdict, balefulInterdictEffect} from './macros/2014/classFeatures/illrigger/balefulInterdict.js';
export {forkedTongue} from './macros/2014/classFeatures/illrigger/forkedTongue.js';
export {combatMasteryBravado} from './macros/2014/classFeatures/illrigger/combatMasteries/bravado.js';
export {combatMasteryBrutal} from './macros/2014/classFeatures/illrigger/combatMasteries/brutal.js';
export {combatMasteryInexorable} from './macros/2014/classFeatures/illrigger/combatMasteries/inexorable.js';
export {combatMasteryLies} from './macros/2014/classFeatures/illrigger/combatMasteries/lies.js';
export {combatMasteryLissome} from './macros/2014/classFeatures/illrigger/combatMasteries/lissome.js';
export {combatMasteryUnfettered} from './macros/2014/classFeatures/illrigger/combatMasteries/unfettered.js';
export {interdictBoonAbatingSeal} from './macros/2014/classFeatures/illrigger/interdictBoons/abatingSeal.js';
export {interdictBoonBedevil} from './macros/2014/classFeatures/illrigger/interdictBoons/bedevil.js';
export {interdictSoulEater} from './macros/2014/classFeatures/illrigger/interdictBoons/soulEater.js';
export {interdictStyxsApathy, interdictStyxsApathyEffect} from './macros/2014/classFeatures/illrigger/interdictBoons/styxsApathy.js';
export {interdictswiftRetribution} from './macros/2014/classFeatures/illrigger/interdictBoons/swiftRetribution.js';
export {infernalConduit} from './macros/2014/classFeatures/illrigger/infernalConduit.js';
export {bloodPrice} from './macros/2014/classFeatures/illrigger/bloodPrice.js';
export {terrorizingForce} from './macros/2014/classFeatures/illrigger/terrorizingForce.js';
export {superiorInterdict} from './macros/2014/classFeatures/illrigger/superiorInterdict.js';
export {infernalMajesty, infernalMajestyEffect} from './macros/2014/classFeatures/illrigger/infernalMajesty.js';
export {masterOfHell} from './macros/2014/classFeatures/illrigger/masterOfHell.js';
// Race Features
export {aasimarNecroticShroud, aasimarRadiantConsumption, aasimarRadiantSoul, celestialRevelation} from './macros/2014/raceFeatures/aasimar/celestialRevelation.js';
export {acidBreathWeapon, coldBreathWeapon, fireBreathWeapon, lightningBreathWeapon, poisonBreathWeapon} from './macros/2014/raceFeatures/dragonborn/chromatic/breathWeapon.js';
export {amorphous} from './macros/2014/raceFeatures/plasmoid/amorphous.js';
export {artisansIntuition} from './macros/2014/raceFeatures/human/markOfMaking/artisansIntuition.js';
export {astralKnowledge} from './macros/2014/raceFeatures/githyanki/astralKnowledge.js';
export {astralSpark} from './macros/2014/raceFeatures/giff/astralSpark.js';
export {astralTrance} from './macros/2014/raceFeatures/astralElf/astralTrance.js';
export {blessingOfTheRavenQueen} from './macros/2014/raceFeatures/shadarKai/blessingOfTheRavenQueen.js';
export {brave} from './macros/2014/raceFeatures/halfling/brave.js';
export {breathWeaponAcid, breathWeaponCold, breathWeaponFire, breathWeaponLightning, metallicBreathWeapon} from './macros/2014/raceFeatures/dragonborn/metallic/breathWeapon.js';
export {breathWeaponBlack, breathWeaponBlue, breathWeaponBrass, breathWeaponBronze, breathWeaponCopper, breathWeaponGold, breathWeaponGreen, breathWeaponRed, breathWeaponSilver, breathWeaponWhite} from './macros/2014/raceFeatures/dragonborn/legacy/breathWeapon.js';
export {breathWeaponForce, breathWeaponNecrotic, breathWeaponPsychic, breathWeaponRadiant, breathWeaponThunder} from './macros/2014/raceFeatures/dragonborn/gem/breathWeapon.js';
export {changeSeason} from './macros/2014/raceFeatures/eladrin/changeSeason.js';
export {chromaticWardingAcid, chromaticWardingCold, chromaticWardingFire, chromaticWardingLightning, chromaticWardingPoison} from './macros/2014/raceFeatures/dragonborn/chromatic/chromaticWarding.js';
export {constructedResilience} from './macros/2014/raceFeatures/warforged/constructedResilience.js';
export {cunningIntuition} from './macros/2014/raceFeatures/elf/markOfShadow/cunningIntuition.js';
export {deductiveIntuition} from './macros/2014/raceFeatures/halfElf/markOfDetection/deductiveIntuition.js';
export {draconicCry} from './macros/2014/raceFeatures/kobold/draconicCry.js';
export {dualMind} from './macros/2014/raceFeatures/kalashtar/dualMind.js';
export {dwarvenResilience} from './macros/2014/raceFeatures/dwarf/dwarvenResilience.js';
export {eladrinFeyStep} from './macros/2014/raceFeatures/eladrin/feyStep.js';
export {everHospitable} from './macros/2014/raceFeatures/halfling/markOfHospitality/everHospitable.js';
export {feyAncestry} from './macros/2014/raceFeatures/multiple/feyAncestry.js';
export {forcefulPresence} from './macros/2014/raceFeatures/dragonborn/draconblood/forcefulPresence.js';
export {gemFlight} from './macros/2014/raceFeatures/dragonborn/gem/gemFlight.js';
export {giftedScribe} from './macros/2014/raceFeatures/gnome/markOfScribing/giftedScribe.js';
export {gnomeCunning} from './macros/2014/raceFeatures/gnome/gnomeCunning.js';
export {hadozeeDodge} from './macros/2014/raceFeatures/hadozee/hadozeeDodge.js';
export {healingHands} from './macros/2014/raceFeatures/aasimar/healingHands.js';
export {hiddenStep} from './macros/2014/raceFeatures/firbolg/hiddenStep.js';
export {hungryJaws} from './macros/2014/raceFeatures/lizardfolk/hungryJaws.js';
export {incisiveSense} from './macros/2014/raceFeatures/elf/pallid/incisiveSense.js';
export {labyrinthineRecall} from './macros/2014/raceFeatures/minotaur/labyrinthineRecall.js';
export {longLimbed} from './macros/2014/raceFeatures/bugbear/longLimbed.js';
export {loxodonSerenity} from './macros/2014/raceFeatures/loxodon/loxodonSerenity.js';
export {luckyFootwork} from './macros/2014/raceFeatures/harengon/luckyFootwork.js';
export {lucky} from './macros/2014/raceFeatures/halfling/lucky.js';
export {medicalIntuition} from './macros/2014/raceFeatures/halfling/markOfHealing/medicalIntuition.js';
export {mentalDisciplineGithzerai} from './macros/2014/raceFeatures/githzerai/mentalDiscipline.js';
export {mentalDisciplineKalashtar} from './macros/2014/raceFeatures/kalashtar/mentalDiscipline.js';
export {naturalResilience} from './macros/2014/raceFeatures/plasmoid/naturalResilience.js';
export {poisonousSkin} from './macros/2014/raceFeatures/grung/poisonousSkin.js';
export {relentlessEndurance} from './macros/2014/raceFeatures/orc/relentlessEndurance.js';
export {savageAttacks} from './macros/2014/raceFeatures/halfOrc/savageAttacks.js';
export {shiftSwiftstride} from './macros/2014/raceFeatures/shifter/shiftSwiftstride.js';
export {shiftWildhunt} from './macros/2014/raceFeatures/shifter/shiftWildhunt.js';
export {spiderClimb} from './macros/2014/raceFeatures/dhampir/spiderClimb.js';
export {starlightStep} from './macros/2014/raceFeatures/astralElf/starlightStep.js';
export {stonesEndurance} from './macros/2014/raceFeatures/goliath/stonesEndurance.js';
export {stoutResilience} from './macros/2014/raceFeatures/halfling/stout/stoutResilience.js';
export {telepathicInsight} from './macros/2014/raceFeatures/verdan/telepathicInsight.js';
export {vampiricBite} from './macros/2014/raceFeatures/dhampir/vampiricBite.js';
export {wardersIntuition} from './macros/2014/raceFeatures/dwarf/markOfWarding/wardersIntuition.js';
export {windwrightsIntuition} from './macros/2014/raceFeatures/halfElf/markOfStorm/windwrightsIntuition.js';
// Monster Features
export {armyArcana} from './macros/2014/monsterFeatures/fey/hobgoblinDevastator/armyArcana.js';
export {causticMist} from './macros/2014/monsterFeatures/monstrosity/hoardMimic/causticMist.js';
export {devastatingBolt} from './macros/2014/monsterFeatures/fey/hobgoblinDevastator/devastatingBolt.js';
export {heatedBody} from './macros/2014/monsterFeatures/heatedBody.js';
export {hoardMimicPseudopod} from './macros/2014/monsterFeatures/monstrosity/hoardMimic/pseudopod.js';
export {leadership, leadershipAura} from './macros/2014/monsterFeatures/fey/hobgoblin/leadership.js';
export {mimicAdhesive} from './macros/2014/monsterFeatures/monstrosity/mimic/adhesive.js';
export {mimicPseudopod} from './macros/2014/monsterFeatures/monstrosity/mimic/pseudopod.js';
export {minotaurCharge} from './macros/2014/monsterFeatures/monstrosity/minotaur/charge.js';
export {minotaurGore} from './macros/2014/monsterFeatures/monstrosity/minotaur/gore.js';
export {regeneration} from './macros/2014/monsterFeatures/regeneration.js';
export {sculptedExplosion} from './macros/2014/monsterFeatures/humanoid/evokerWizard/sculptedExplosion.js';
export {shieldBash} from './macros/2014/monsterFeatures/fey/hobgoblinWarlord/shieldBash.js';
export {shieldGuardianBound} from './macros/2014/monsterFeatures/construct/shieldGuardian/bound.js';
export {shieldGuardianShield, shieldGuardianShieldEffect} from './macros/2014/monsterFeatures/construct/shieldGuardian/shield.js';
export {shieldGuardianSpellStoring} from './macros/2014/monsterFeatures/construct/shieldGuardian/spellStoring.js';
export {spittingMimicAcid} from './macros/2014/monsterFeatures/monstrosity/spittingMimic/spitAcid.js';
export {thunderousStrike} from './macros/2014/monsterFeatures/elemental/earthElementalMyrmidon/thunderousStrike.js';
// Generic Monster Features
export {abilityDrain} from './macros/2014/monsterFeatures/generic/abilityDrain.js';
export {activityOnEffectExpiry} from './macros/2014/monsterFeatures/generic/activityOnEffectExpiry.js';
export {activityOnRest, activityOnRestActor} from './macros/2014/monsterFeatures/generic/activityOnRest.js';
export {advantageDamageBonus} from './macros/2014/monsterFeatures/generic/advantageDamageBonus.js';
export {auraDamageEnd} from './macros/2014/monsterFeatures/generic/auraDamage.js';
export {autoGrapple} from './macros/2014/monsterFeatures/generic/autoGrapple.js';
export {autoPush} from './macros/2014/monsterFeatures/generic/autoPush.js';
export {berserk} from './macros/2014/monsterFeatures/generic/berserk.js';
export {bloodFrenzy} from './macros/2014/monsterFeatures/generic/bloodFrenzy.js';
export {bloodiedFrenzy} from './macros/2014/monsterFeatures/generic/bloodiedFrenzy.js';
export {chooseDamageType} from './macros/2014/monsterFeatures/generic/chooseDamageType.js';
export {contextualBonus} from './macros/2014/monsterFeatures/generic/contextualBonus.js';
export {damageTurnStart} from './macros/2014/monsterFeatures/generic/damageTurnStart.js';
export {deathBurst} from './macros/2014/monsterFeatures/generic/deathBurst.js';
export {effectImmunity, effectImmunityRemove} from './macros/2014/monsterFeatures/generic/effectImmunity.js';
export {enlarge, enlargeEnlarged} from './macros/2014/monsterFeatures/generic/enlarge.js';
export {escape} from './macros/2014/monsterFeatures/generic/escape.js';
export {failedByAmount} from './macros/2014/monsterFeatures/generic/failedByAmount.js';
export {gaze} from './macros/2014/monsterFeatures/generic/gaze.js';
export {genericRegeneration} from './macros/2014/monsterFeatures/generic/regeneration.js';
export {genericTeleport} from './macros/2014/monsterFeatures/generic/teleport.js';
export {keenSenses} from './macros/2014/monsterFeatures/generic/keenSenses.js';
export {lifesteal} from './macros/2014/monsterFeatures/generic/lifesteal.js';
export {martialAdvantage} from './macros/2014/monsterFeatures/generic/martialAdvantage.js';
export {movementBonusActivity} from './macros/2014/monsterFeatures/generic/movementBonusActivity.js';
export {packTactics} from './macros/2014/monsterFeatures/generic/packTactics.js';
export {parry} from './macros/2014/monsterFeatures/generic/parry.js';
export {reduce, reduceReduced} from './macros/2014/monsterFeatures/generic/reduce.js';
export {reduceMaxHP} from './macros/2014/monsterFeatures/generic/reduceMaxHP.js';
export {rerollSaveOnDamage, rerollSaveOnDamageActor} from './macros/2014/monsterFeatures/generic/rerollSaveOnDamage.js';
export {rollForActivity} from './macros/2014/monsterFeatures/generic/rollForActivity.js';
export {specialItemUse} from './macros/2014/monsterFeatures/generic/specialItemUse.js';
export {spellTurning} from './macros/2014/monsterFeatures/generic/spellTurning.js';
export {suffocate} from './macros/2014/monsterFeatures/generic/suffocate.js';
export {sunlightSensitivity} from './macros/2014/monsterFeatures/generic/sunlightSensitivity.js';
export {surpriseAttack} from './macros/2014/monsterFeatures/generic/surpriseAttack.js';
export {swarmDamage} from './macros/2014/monsterFeatures/generic/swarmDamage.js';
export {touchDamage} from './macros/2014/monsterFeatures/generic/touchDamage.js';
export {undeadFortitude} from './macros/2014/monsterFeatures/generic/undeadFortitude.js';
// Actions
export {checkCover} from './macros/2014/actions/checkCover.js';
export {dash} from './macros/2014/actions/dash.js';
export {disengage} from './macros/2014/actions/disengage.js';
export {dodge} from './macros/2014/actions/dodge.js';
export {fall} from './macros/2014/actions/fall.js';
export {grapple, grappleEscape} from './macros/2014/actions/grapple.js';
export {help} from './macros/2014/actions/help.js';
export {hide, hideEffect} from './macros/2014/actions/hide.js';
export {readyAction} from './macros/2014/actions/readyAction.js';
export {readySpell} from './macros/2014/actions/readySpell.js';
export {search} from './macros/2014/actions/search.js';
export {shove} from './macros/2014/actions/shove.js';
export {squeeze} from './macros/2014/actions/squeeze.js';
export {stabilize} from './macros/2014/actions/stabilize.js';
export {underwater, underwaterEffect} from './macros/2014/actions/underwater.js';
// Feats
export {aberrantDragonmark} from './macros/2014/feats/aberrantDragonmark.js';
export {bulwark} from './macros/2014/feats/bulwark.js';
export {chromaticInfusion, reactiveResistance} from './macros/2014/feats/giftOfTheChromaticDragon.js';
export {cloudyEscape} from './macros/2014/feats/cloudyEscape.js';
export {crusher} from './macros/2014/feats/crusher.js';
export {dualWielder} from './macros/2014/feats/dualWielder.js';
export {elementalAdeptA, elementalAdeptC, elementalAdeptF, elementalAdeptL, elementalAdeptT} from './macros/2014/feats/elementalAdept.js';
export {frigidRetaliation} from './macros/2014/feats/frigidRetaliation.js';
export {grappler, grapplerPin} from './macros/2014/feats/grappler.js';
export {graspOfAvarice} from './macros/2014/feats/graspOfAvarice.js';
export {heavyArmorMaster} from './macros/2014/feats/heavyArmorMaster.js';
export {imbueCard} from './macros/2014/feats/imbueCard.js';
export {maelstromAura} from './macros/2014/feats/maelstromAura.js';
export {martialAdept} from './macros/2014/feats/martialAdept.js';
export {orcishFury} from './macros/2014/feats/orcishFury.js';
export {piercer} from './macros/2014/feats/piercer.js';
export {planarAdaptation, portalCracker} from './macros/2014/feats/planarWanderer.js';
export {remarkableRecovery} from './macros/2014/feats/remarkableRecovery.js';
export {savageAttacker} from './macros/2014/feats/savageAttacker.js';
export {scionChaotic, scionGood, scionEvil, scionLawful, scionOutlands} from './macros/2014/feats/scionPlanes.js';
export {searingIgnition} from './macros/2014/feats/searingIgnition.js';
export {sharpshooter} from './macros/2014/feats/sharpshooter.js';
export {slasher} from './macros/2014/feats/slasher.js';
export {soothePain} from './macros/2014/feats/soothePain.js';
export {stasisStrike} from './macros/2014/feats/stasisStrike.js';
export {stoneThrow} from './macros/2014/feats/stoneThrow.js';
export {strikeOfTheGiants, cloudStrike, fireStrike, frostStrike, hillStrike, stoneStrike, stormStrike} from './macros/2014/feats/strikeOfTheGiants.js';
export {tavernBrawler, tavernBrawlerUnarmedStrike} from './macros/2014/feats/tavernBrawler.js';
export {telekineticShove} from './macros/2014/feats/telekinetic.js';
// Items
export {allPurposeTool1, allPurposeTool2, allPurposeTool3} from './macros/2014/items/trinket/allPurposeTool.js';
export {armorOfSafeguardingP, armorOfSafeguardingC, armorOfSafeguardingR, armorOfSafeguardingS} from './macros/2014/items/armor/armorOfSafeguarding.js';
export {badNews} from './macros/2014/items/weapons/badNews.js';
export {bigbysBeneficentBracelet} from './macros/2014/items/trinket/bigbysBeneficentBracelet.js';
export {blackrazor} from './macros/2014/items/weapons/blackrazor.js';
export {bloodSpear} from './macros/2014/items/weapons/bloodSpear.js';
export {blunderbuss} from './macros/2014/items/weapons/blunderbuss.js';
export {bootsOfElvenkind} from './macros/2014/items/trinket/bootsOfElvenkind.js';
export {crystalBlade, crystalBladeGreatsword, crystalBladeLongsword, crystalBladeRapier, crystalBladeScimitar, crystalBladeShortsword} from './macros/2014/items/weapons/crystalBlade.js';
export {dancingSword, dancingSwordGreatsword, dancingSwordLongsword, dancingSwordRapier, dancingSwordScimitar, dancingSwordShortsword} from './macros/2014/items/weapons/dancingSword.js';
export {danothsVisorD, danothsVisorA, danothsVisorE} from './macros/2014/items/trinket/danothsVisor.js';
export {dragonTouchedFocusSlumbering, dragonTouchedFocusStirringChromatic, dragonTouchedFocusStirringGem} from './macros/2014/items/trinket/dragonTouchedFocus.js';
export {dragonVessel, dragonVessel0, dragonVessel1, dragonVessel2, dragonVessel3} from './macros/2014/items/trinket/dragonVessel.js';
export {dragonsWrath, dragonsWrath0, dragonsWrath1, dragonsWrath2, dragonsWrath3} from './macros/2014/items/weapons/dragonsWrath.js';
export {eldritchClawTattoo} from './macros/2014/items/trinket/eldritchClawTattoo.js';
export {elixirOfHealth} from './macros/2014/items/consumable/elixirOfHealth.js';
export {eyesOfMinuteSeeing} from './macros/2014/items/trinket/eyesOfMinuteSeeing.js';
export {eyesOfTheEagle} from './macros/2014/items/trinket/eyesOfTheEagle.js';
export {firearm, firearmReload, firearmRepair} from './macros/2014/mechanics/firearm.js';
export {grovelthrash, grovelthrash0, grovelthrash1, grovelthrash2} from './macros/2014/items/weapons/grovelthrash.js';
export {guardianEmblem} from './macros/2014/items/trinket/guardianEmblem.js';
export {insigniaOfClaws} from './macros/2014/items/trinket/insigniaOfClaws.js';
export {javelinOfLightning} from './macros/2014/items/weapons/javelinOfLightning.js';
export {lanternOfRevealing} from './macros/2014/items/trinket/lanternOfRevealing.js';
export {lastStandArmorBR, lastStandArmorCM, lastStandArmorCS, lastStandArmorH, lastStandArmorHP, lastStandArmorL, lastStandArmorP, lastStandArmorPl, lastStandArmorRM, lastStandArmorS, lastStandArmorSL, lastStandArmorSM} from './macros/2014/items/armor/lastStandArmor.js';
export {mastersAmulet} from './macros/2014/items/trinket/mastersAmulet.js';
export {musket} from './macros/2014/items/weapons/musket.js';
export {mysteryKey} from './macros/2014/items/trinket/mysteryKey.js';
export {oilOfSharpness} from './macros/2014/items/consumable/oilOfSharpness.js';
export {palmPistol} from './macros/2014/items/weapons/palmPistol.js';
export {pariahsShield} from './macros/2014/items/armor/pariahsShield.js';
export {pepperbox} from './macros/2014/items/weapons/pepperbox.js';
export {pistol} from './macros/2014/items/weapons/pistol.js';
export {potionOfAdvantage} from './macros/2014/items/consumable/potionOfAdvantage.js';
export {potionOfAqueousForm} from './macros/2014/items/consumable/potionOfAqueousForm.js';
export {potionOfDiminution} from './macros/2014/items/consumable/potionOfDiminution.js';
export {potionOfFireBreath, potionOfFireBreathAttack} from './macros/2014/items/consumable/potionOfFireBreath.js';
export {potionOfGiantSize} from './macros/2014/items/consumable/potionOfGiantSize.js';
export {potionOfGrowth} from './macros/2014/items/consumable/potionOfGrowth.js';
export {potionOfHeroism} from './macros/2014/items/consumable/potionOfHeroism.js';
export {potionOfInvisibility} from './macros/2014/items/consumable/potionOfInvisibility.js';
export {potionOfInvulnerability} from './macros/2014/items/consumable/potionOfInvulnerability.js';
export {potionOfMaximumPower} from './macros/2014/items/consumable/potionOfMaximumPower.js';
export {potionOfPoison} from './macros/2014/items/consumable/potionOfPoison.js';
export {potionOfSpeed} from './macros/2014/items/consumable/potionOfSpeed.js';
export {potionOfVitality} from './macros/2014/items/consumable/potionOfVitality.js';
export {ringOfSpellStoring, ringOfSpellStoringSpell} from './macros/2014/items/trinket/ringOfSpellStoring.js';
export {stormgirdleD, stormgirdleA, stormgirdleE, stormAvatar} from './macros/2014/items/trinket/stormgirdle.js';
export {titanstoneKnucklesD, titanstoneKnucklesA, titanstoneKnucklesE} from './macros/2014/items/trinket/titanstoneKnuckles.js';
export {unarmedStrike} from './macros/2014/items/misc/unarmedStrike.js';
export {wandOfTheWarMage, wandOfTheWarMage1, wandOfTheWarMage2, wandOfTheWarMage3} from './macros/2014/items/trinket/wandOfTheWarMage.js';
export {wingsOfFlying, wingsOfFlyingEffect, wingsOfFlyingRecharge} from './macros/2014/items/clothing/wingsOfFlying.js';
export {wrapsOfDyamak, wrapsOfDyamak0, wrapsOfDyamak1, wrapsOfDyamak2, crimsonMist} from './macros/2014/items/trinket/wrapsOfDyamak.js';
//BG3 Weapon Actions
export {backbreaker, braceMelee, braceMeleeDamage, cleave, concussiveSmash, maimingStrike, disarmingStrike, flourish, heartstopper, lacerate, piercingStrike, piercingStrikeEffect, pommelStrike, prepare, rush, tenacity, topple, weakeningStrike, braceRanged, braceRangedDamage, hamstringShot, mobileShot, piercingShot} from './macros/2014/homebrew/bg3WeaponActions.js';
//Other
export {maxDamage, maxDamageEffect, doubleDamage, doubleDamageEffect} from './macros/homebrew/critFumble.js';
