// Generic Monster Features
export {advantageDamageBonus} from './macros/2014/monsterFeatures/generic/advantageDamageBonus.js';
export {auraDamageEnd} from './macros/2014/monsterFeatures/generic/auraDamage.js';
export {autoGrapple} from './macros/2014/monsterFeatures/generic/autoGrapple.js';
export {berserk} from './macros/2014/monsterFeatures/generic/berserk.js';
export {contextualBonus} from './macros/2014/monsterFeatures/generic/contextualBonus.js';
export {damageTurnStart} from './macros/2014/monsterFeatures/generic/damageTurnStart.js';
export {deathBurst} from './macros/2014/monsterFeatures/generic/deathBurst.js';
export {enlarge, enlargeEnlarged} from './macros/2014/monsterFeatures/generic/enlarge.js';
export {gaze} from './macros/2014/monsterFeatures/generic/gaze.js';
export {genericRegeneration} from './macros/2014/monsterFeatures/generic/regeneration.js';
export {genericTeleport} from './macros/2014/monsterFeatures/generic/teleport.js';
export {keenSenses} from './macros/2014/monsterFeatures/generic/keenSenses.js';
export {packTactics} from './macros/2014/monsterFeatures/generic/packTactics.js';
export {reduce, reduceReduced} from './macros/2014/monsterFeatures/generic/reduce.js';
export {reduceMaxHP} from './macros/2014/monsterFeatures/generic/reduceMaxHP.js';
export {spellTurning} from './macros/2014/monsterFeatures/generic/spellTurning.js';
export {abilityDrain} from './macros/2014/monsterFeatures/generic/abilityDrain.js';
export {sunlightSensitivity} from './macros/2014/monsterFeatures/generic/sunlightSensitivity.js';
export {surpriseAttack} from './macros/2014/monsterFeatures/generic/surpriseAttack.js';
export {swarmDamage} from './macros/2014/monsterFeatures/generic/swarmDamage.js';
export {touchDamage} from './macros/2014/monsterFeatures/generic/touchDamage.js';
export {undeadFortitude} from './macros/2014/monsterFeatures/generic/undeadFortitude.js';
export {martialAdvantage} from './macros/2014/monsterFeatures/generic/martialAdvantage.js';
export {parry} from './macros/2014/monsterFeatures/generic/parry.js';
export {lifesteal} from './macros/2014/monsterFeatures/generic/lifesteal.js';
export {effectImmunity, effectImmunityRemove} from './macros/2014/monsterFeatures/generic/effectImmunity.js';
export {autoPush} from './macros/2014/monsterFeatures/generic/autoPush.js';
//Mechanics
export {invisible} from './macros/2024/mechanics/invisible.js';
export {cleaveMastery, grazeMastery, pushMastery, sapMastery, slowMastery, toppleMastery, vexMastery} from './macros/2024/mechanics/masteries.js';
//Generic
export {proneOnFail} from './macros/2024/generic/proneOnFail.js';
//Spells
export {acidArrow} from './macros/2024/spells/acidArrow.js';
export {acidSplash} from './macros/2024/spells/acidSplash.js';
export {aid} from './macros/2024/spells/aid.js';
export {alterSelf} from './macros/2024/spells/alterSelf.js';
export {animalFriendship} from './macros/2024/spells/animalFriendship.js';
export {animalMessenger} from './macros/2024/spells/animalMessenger.js';
export {animateDead} from './macros/2024/spells/animateDead.js';
export {antilifeShell, antilifeShellOtherMove} from './macros/2024/spells/antilifeShell.js';
export {arcaneVigor} from './macros/2024/spells/arcaneVigor.js';
export {armorOfAgathys} from './macros/2024/spells/armorOfAgathys.js';
export {armsOfHadar} from './macros/2024/spells/armsOfHadar.js';
export {auraOfLife} from './macros/2024/spells/auraOfLife.js';
export {auraOfPurity, auraOfPurityAura} from './macros/2024/spells/auraOfPurity.js';
export {auraOfVitality, auraOfVitalityEffect} from './macros/2024/spells/auraOfVitality.js';
export {bane} from './macros/2024/spells/bane.js';
export {banishingSmite} from './macros/2024/spells/banishingSmite.js';
export {banishment, banishmentBanished} from './macros/2024/spells/banishment.js';
export {barkskin} from './macros/2024/spells/barkskin.js';
export {beaconOfHope} from './macros/2024/spells/beaconOfHope.js';
export {bestowCurse} from './macros/2024/spells/bestowCurse.js';
export {bladeWard} from './macros/2024/spells/bladeWard.js';
export {bless} from './macros/2024/spells/bless.js';
export {blight} from './macros/2024/spells/blight.js';
export {blindingSmite} from './macros/2024/spells/blindingSmite.js';
export {blindnessDeafness} from './macros/2024/spells/blindnessDeafness.js';
export {blink, blinkBlinking, blinkBlinkedAway} from './macros/2024/spells/blink.js';
export {blur, blurEffect} from './macros/2024/spells/blur.js';
export {burningHands} from './macros/2024/spells/burningHands.js';
export {callLightning} from './macros/2024/spells/callLightning.js';
export {calmEmotions} from './macros/2024/spells/calmEmotions.js';
export {chainLightning} from './macros/2024/spells/chainLightning.js';
export {charmMonster} from './macros/2024/spells/charmMonster.js';
export {charmPerson} from './macros/2024/spells/charmPerson.js';
export {chillTouch} from './macros/2024/spells/chillTouch.js';
export {chromaticOrb} from './macros/2024/spells/chromaticOrb.js';
export {circleOfDeath} from './macros/2024/spells/circleOfDeath.js';
export {cloudkill, cloudkillSource, cloudkillCloud} from './macros/2024/spells/cloudkill.js';
export {command, commandTurnStart, commandGrovel} from './macros/2024/spells/command.js';
export {compelledDuel, compelledDuelCompelled, compelledDuelSource} from './macros/2024/spells/compelledDuel.js';
export {crownOfMadness} from './macros/2024/spells/crownOfMadness.js';
export {crusadersMantle} from './macros/2024/spells/crusadersMantle.js';
export {darkness} from './macros/2024/spells/darkness.js';
export {deathWard} from './macros/2024/spells/deathWard.js';
export {destructiveWave} from './macros/2024/spells/destructiveWave.js';
export {detectMagic} from './macros/2024/spells/detectMagic.js';
export {disintegrate} from './macros/2024/spells/disintegrate.js';
export {divineSmite} from './macros/2024/spells/divineSmite.js';
export {dragonsBreath} from './macros/2024/spells/dragonsBreath.js';
export {eldritchBlast} from './macros/2024/spells/eldritchBlast.js';
export {elementalWeapon} from './macros/2024/spells/elementalWeapon.js';
export {enlargeReduce} from './macros/2024/spells/enlargeReduce.js';
export {faerieFire} from './macros/2024/spells/faerieFire.js';
export {findFamiliar} from './macros/2024/spells/findFamiliar.js';
export {fireShield} from './macros/2024/spells/fireShield.js';
export {fireStorm} from './macros/2024/spells/fireStorm.js';
export {flameBlade} from './macros/2024/spells/flameBlade.js';
export {flamingSphere} from './macros/2024/spells/flamingSphere.js';
export {fly} from './macros/2024/spells/fly.js';
export {fogCloud} from './macros/2024/spells/fogCloud.js';
export {gaseousForm} from './macros/2024/spells/gaseousForm.js';
export {globeOfInvulnerability, globeOfInvulnerabilityInvulnerable} from './macros/2024/spells/globeOfInvulnerability.js';
export {grease} from './macros/2024/spells/grease.js';
export {guardianOfFaith} from './macros/2024/spells/guardianOfFaith.js';
export {guidingBolt} from './macros/2024/spells/guidingBolt.js';
export {gustOfWind, gustOfWindGust} from './macros/2024/spells/gustOfWind.js';
export {heatMetal} from './macros/2024/spells/heatMetal.js';
export {heroism, heroismHeroic} from './macros/2024/spells/heroism.js';
export {hex} from './macros/2024/spells/hex.js';
export {holdPerson} from './macros/2024/spells/holdPerson.js';
export {hungerOfHadar, hungerOfHadarTemplate} from './macros/2024/spells/hungerOfHadar.js';
export {huntersMark, huntersMarkSource} from './macros/2024/spells/huntersMark.js';
export {hypnoticPattern} from './macros/2024/spells/hypnoticPattern.js';
export {iceStorm} from './macros/2024/spells/iceStorm.js';
export {insectPlague, insectPlagueTemplate} from './macros/2024/spells/insectPlague.js';
export {magicMissile} from './macros/2024/spells/magicMissile.js';
export {massCureWounds} from './macros/2024/spells/massCureWounds.js';
export {mindSliver} from './macros/2024/spells/mindSliver.js';
export {mirrorImage, mirrorImageMirrored} from './macros/2024/spells/mirrorImage.js';
export {mistyStep} from './macros/2024/spells/mistyStep.js';
export {moonbeam, moonbeamBeam} from './macros/2024/spells/moonbeam.js';
export {passWithoutTrace} from './macros/2024/spells/passWithoutTrace.js';
export {powerWordHeal} from './macros/2024/spells/powerWordHeal.js';
export {powerWordKill} from './macros/2024/spells/powerWordKill.js';
export {protectionFromEvilAndGood} from './macros/2024/spells/protectionFromEvilAndGood.js';
export {sanctuary, sanctuarySafe} from './macros/2024/spells/sanctuary.js';
export {scorchingRay} from './macros/2024/spells/scorchingRay.js';
export {searingSmite} from './macros/2024/spells/searingSmite.js';
export {shield} from './macros/2024/spells/shield.js';
export {shieldOfFaith} from './macros/2024/spells/shieldOfFaith.js';
export {shiningSmite} from './macros/2024/spells/shiningSmite.js';
export {shockingGrasp} from './macros/2024/spells/shockingGrasp.js';
export {sleetStorm, sleetStormArea} from './macros/2024/spells/sleetStorm.js';
export {spikeGrowth} from './macros/2024/spells/spikeGrowth.js';
export {spiritGuardians, spiritGuardiansDamage} from './macros/2024/spells/spiritGuardians.js';
export {spiritualWeapon} from './macros/2024/spells/spiritualWeapon.js';
export {staggeringSmite} from './macros/2024/spells/staggeringSmite.js';
export {summonAberration, summonAberrationWhisperingAura} from './macros/2024/spells/summonAberration.js';
export {summonBeast} from './macros/2024/spells/summonBeast.js';
export {summonCelestial, summonCelestialMace} from './macros/2024/spells/summonCelestial.js';
export {summonConstruct, summonConstructMetal, summonConstructStone} from './macros/2024/spells/summonConstruct.js';
export {summonDragon} from './macros/2024/spells/summonDragon.js';
export {summonElemental} from './macros/2024/spells/summonElemental.js';
export {summonFey, summonFeyFeyStep} from './macros/2024/spells/summonFey.js';
export {summonFiend, summonFiendClaws, summonFiendDeathThroes} from './macros/2024/spells/summonFiend.js';
export {summonUndead, summonUndeadPutrid} from './macros/2024/spells/summonUndead.js';
export {synapticStatic} from './macros/2024/spells/synapticStatic.js';
export {teleport} from './macros/2024/spells/teleport.js';
export {thornWhip} from './macros/2024/spells/thornWhip.js';
export {thunderousSmite} from './macros/2024/spells/thunderousSmite.js';
export {thunderwave} from './macros/2024/spells/thunderwave.js';
export {tollTheDead} from './macros/2024/spells/tollTheDead.js';
export {trueStrike} from './macros/2024/spells/trueStrike.js';
export {vampiricTouch} from './macros/2024/spells/vampiricTouch.js';
export {vitriolicSphere} from './macros/2024/spells/vitriolicSphere.js';
export {wallOfFire} from './macros/2024/spells/wallOfFire.js';
export {wardingBond} from './macros/2024/spells/wardingBond.js';
export {wish, wishStress, wishImmunity} from './macros/2024/spells/wish.js';
export {wrathfulSmite} from './macros/2024/spells/wrathfulSmite.js';
export {zoneOfTruth} from './macros/2024/spells/zoneOfTruth.js';
//Items
export {unarmedStrike} from './macros/2024/items/misc/unarmedStrike.js';
//Feats
export {crusher} from './macros/2024/feats/crusher.js';
//Class Features
//Barbarian
export {rage, rageRaging, rageUpkeep} from './macros/2024/classFeatures/barbarian/rage.js';
export {unarmoredDefenseBarbarian} from './macros/2024/classFeatures/barbarian/unarmoredDefense.js';
export {dangerSense} from './macros/2024/classFeatures/barbarian/dangerSense.js';
export {recklessAttack} from './macros/2024/classFeatures/barbarian/recklessAttack.js';
export {primalKnowledge} from './macros/2024/classFeatures/barbarian/primalKnowledge.js';
export {feralInstinct} from './macros/2024/classFeatures/barbarian/feralInstinct.js';
export {brutalStrike, sunderingBlow} from './macros/2024/classFeatures/barbarian/brutalStrike.js';
export {relentlessRage} from './macros/2024/classFeatures/barbarian/relentlessRage.js';
export {improvedBrutalStrike} from './macros/2024/classFeatures/barbarian/improvedBrutalStrike.js';
export {persistentRage} from './macros/2024/classFeatures/barbarian/persistentRage.js';
export {indomitableMight} from './macros/2024/classFeatures/barbarian/indomitableMight.js';
//Path of the Berserker
export {frenzy} from './macros/2024/classFeatures/barbarian/berserker/frenzy.js';
export {mindlessRage} from './macros/2024/classFeatures/barbarian/berserker/mindlessRage.js';
export {retaliation} from './macros/2024/classFeatures/barbarian/berserker/retaliation.js';
export {intimidatingPresence} from './macros/2024/classFeatures/barbarian/berserker/intimidatingPresence.js';
//Path of the Wild Heart
export {rageOfTheWilds, rageOfTheWildsWolf} from './macros/2024/classFeatures/barbarian/wildHeart/rageOfTheWilds.js';
export {aspectOfTheWilds} from './macros/2024/classFeatures/barbarian/wildHeart/aspectOfTheWilds.js';
export {powerOfTheWilds, powerOfTheWildsLion, powerOfTheWildsRam} from './macros/2024/classFeatures/barbarian/wildHeart/powerOfTheWilds.js';
//Path of the World Tree
export {vitalityOfTheTree, lifeGivingForce} from './macros/2024/classFeatures/barbarian/worldTree/vitalityOfTheTree.js';
export {branchesOfTheTree} from './macros/2024/classFeatures/barbarian/worldTree/branchesOfTheTree.js';
export {batteringRoots} from './macros/2024/classFeatures/barbarian/worldTree/batteringRoots.js';
export {travelAlongTheTree} from './macros/2024/classFeatures/barbarian/worldTree/travelAlongTheTree.js';
//Path of the Zealot
export {divineFury, divineFuryAttack} from './macros/2024/classFeatures/barbarian/zealot/divineFury.js';
export {warriorOfTheGods} from './macros/2024/classFeatures/barbarian/zealot/warriorOfTheGods.js';
export {fanaticalFocus} from './macros/2024/classFeatures/barbarian/zealot/fanaticalFocus.js';
export {zealousPresence} from './macros/2024/classFeatures/barbarian/zealot/zealousPresence.js';
export {rageOfTheGods, rageOfTheGodsEffect} from './macros/2024/classFeatures/barbarian/zealot/rageOfTheGods.js';
//Bard
export {bardicInspiration, bardicInspirationEffect} from './macros/2024/classFeatures/bard/bardicInspiration.js';
export {jackOfAllTrades} from './macros/2024/classFeatures/bard/jackOfAllTrades.js';
export {fontOfInspiration} from './macros/2024/classFeatures/bard/fontOfInspiration.js';
export {countercharm} from './macros/2024/classFeatures/bard/countercharm.js';
export {superiorInspiration} from './macros/2024/classFeatures/bard/superiorInspiration.js';
export {wordsOfCreation} from './macros/2024/classFeatures/bard/wordsOfCreation.js';
//College of Dance
export {dazzlingFootwork} from './macros/2024/classFeatures/bard/dance/dazzlingFootwork.js';
export {inspiringMovement} from './macros/2024/classFeatures/bard/dance/inspiringMovement.js';
export {tandemFootwork} from './macros/2024/classFeatures/bard/dance/tandemFootwork.js';
export {leadingEvasion} from './macros/2024/classFeatures/bard/dance/leadingEvasion.js';
//College of Glamour
export {beguilingMagic} from './macros/2024/classFeatures/bard/glamour/beguilingMagic.js';
export {mantleOfInspiration} from './macros/2024/classFeatures/bard/glamour/mantleOfInspiration.js';
export {mantleOfMajesty, mantleOfMajestyCommand} from './macros/2024/classFeatures/bard/glamour/mantleOfMajesty.js';
export {unbreakableMajesty, unbreakableMajestyEffect} from './macros/2024/classFeatures/bard/glamour/unbreakableMajesty.js';
//College of Lore
export {cuttingWords} from './macros/2024/classFeatures/bard/lore/cuttingWords.js';
export {peerlessSkill} from './macros/2024/classFeatures/bard/lore/peerlessSkill.js';
//College of Valor
export {combatInspiration} from './macros/2024/classFeatures/bard/valor/combatInspiration.js';
//Cleric
export {thaumaturge} from './macros/2024/classFeatures/cleric/thaumaturge.js';
export {channelDivinity} from './macros/2024/classFeatures/cleric/channelDivinity.js';
export {searUndead} from './macros/2024/classFeatures/cleric/searUndead.js';
export {divineStrike} from './macros/2024/classFeatures/cleric/divineStrike.js';
export {potentSpellcasting} from './macros/2024/classFeatures/cleric/potentSpellcasting.js';
export {improvedBlessedStrikes} from './macros/2024/classFeatures/cleric/improvedBlessedStrikes.js';
export {divineIntervention} from './macros/2024/classFeatures/cleric/divineIntervention.js';
export {greaterDivineIntervention, greaterDivineInterventionRest} from './macros/2024/classFeatures/cleric/greaterDivineIntervention.js';
//Life Cleric
export {discipleOfLife} from './macros/2024/classFeatures/cleric/life/discipleOfLife.js';
export {preserveLife} from './macros/2024/classFeatures/cleric/life/preserveLife.js';
export {blessedHealer} from './macros/2024/classFeatures/cleric/life/blessedHealer.js';