name: Release Creation

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v7
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        
    # Install dependencies
    - run: npm ci
    
    # Compendiums are currently non-existent
    #- name: Build Compendiums
    #  run: npm run buildCompendiums
      
    - name: Webpack build
      run: npm run build

    # Remove the 'v' from the tag for versioning
    - id: get_version
      run: |
        echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        echo "FOUNDRY_MANIFEST=https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json" >> $GITHUB_ENV
        echo "FOUNDRY_DOWNLOAD=https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip" >> $GITHUB_ENV

    # Generate module.json
    - name: Generate and Update Manifest
      run: |
        jq --arg version "${{ env.VERSION }}" \
           --arg manifest "${{ env.FOUNDRY_MANIFEST }}" \
           --arg download "${{ env.FOUNDRY_DOWNLOAD }}" \
           '.version = $version | .manifest = $manifest | .download = $download' \
           module-template.json > module.json

    # create a zip file with all files required by the module to add to the release
    - run: zip -r ./module.zip module.json dist packs styles templates LICENSE lang images CHANGELOG.md
    
    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: ${{github.event.release.name}}
        draft: false
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{secrets.GITHUB_TOKEN}}
        artifacts: './module.json, ./module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
        
    - name: FoundryVTT AutoPublish
      if: github.event.release.prerelease == false
      uses: fjogeleit/http-request-action@v2
      continue-on-error: true
      with:
        url: 'https://foundryvtt.com/_api/packages/release_version/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization" : "${{ secrets.FOUNDRY_KEY }}"}'
        data: '{"dry_run": false, "id" : "chris-premades", "release": {"version" :  "${{env.VERSION}}", "manifest": "${{env.FOUNDRY_MANIFEST}}", "notes" : "https://github.com/chrisk123999/chris-premades/blob/master/CHANGELOG.md", "compatibility" : {"minimum": "14", "verified": "14", "maximum": "14"} } }'